// IW9 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

initstructs()
{
    level.struct = [];
}

createstruct()
{
    struct = spawnstruct();
    level.struct[level.struct.size] = struct;
    return struct;
}
