// S4 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

_id_20F2()
{
    level._id_454D = [];
    level._id_01AF = getentarray( "flag_primary", "targetname" );

    foreach ( var_1 in level._id_01AF )
    {
        switch ( var_1._id_CD8C )
        {
            case "_a":
                level._id_454D[game["attackers"]] = var_1.origin;
                break;
            case "_b":
                level._id_4540 = var_1.origin;
                break;
            case "_c":
                level._id_454D[game["defenders"]] = var_1.origin;
                break;
        }
    }
}

_id_2109()
{
    level._id_210C = ( 1000, 1000, 1000 );
    level._id_210B = ( -1000, -1000, -1000 );
    var_0 = _func_0075();

    if ( var_0.size > 0 )
    {
        foreach ( var_2 in var_0 )
        {
            level._id_210C = _id_07EE::_id_5783( level._id_210C, var_2.origin );
            level._id_210B = _id_07EE::_id_5782( level._id_210B, var_2.origin );
        }
    }
    else
    {
        level._id_210C = level._id_E324;
        level._id_210B = level._id_E321;
    }
}

_id_20EF()
{
    if ( !isdefined( level._id_48BE ) )
        level._id_48BE = 0;

    var_0 = _id_68D5();
    level._id_2134 = _id_68D6();
    _id_3529( var_0 );

    if ( var_0.size > 1 && level._id_CB1D > 1 )
    {
        for ( var_1 = 0; var_1 < level._id_CB1D; var_1++ )
        {
            var_2 = _id_68D4( var_0[var_1] );
            _id_20E3( var_2 );
        }
    }
    else
    {
        var_3 = [];
        var_3[0] = ( 0, 0, 0 );
        var_3[1] = ( 50, 0, 0 );
        var_3[2] = ( -50, 0, 0 );
        var_3[3] = ( 0, 50, 0 );
        var_3[4] = ( 0, -50, 0 );

        for ( var_1 = 0; var_1 < level._id_CB1D; var_1++ )
        {
            var_2 = _id_68D4( var_0[var_1] );
            _id_20E3( var_2 + var_3[var_1] );
        }
    }

    level thread _id_0A67::_id_7022();
}

_id_3529( var_0 )
{
    if ( level.mapname == "mp_divide" )
    {
        var_0[0].origin = ( -261, 235, 610 );
        var_0[1].origin = ( -211, 235, 610 );
        var_0[2].origin = ( -311, 235, 610 );
        var_0[3].origin = ( -311, 500, 610 );
        var_0[4].origin = ( -211, 500, 610 );
    }
}

_id_68D5()
{
    var_0 = undefined;

    if ( scripts\mp\utility\game::getgametype() == "tdef" )
        var_0 = scripts\engine\utility::_id_6D7C( "tdef_ball_start", "targetname" );

    if ( !isdefined( var_0 ) || !var_0.size )
        var_0 = scripts\engine\utility::_id_6D7C( "ball_start", "targetname" );

    if ( level._id_CB1D > 1 )
        var_0 = _id_E028( var_0 );

    return var_0;
}

_id_68D6()
{
    var_0 = undefined;

    if ( scripts\mp\utility\game::getgametype() == "tdef" )
        var_0 = getentarray( "tdef_ball_pickup", "targetname" );

    if ( !isdefined( var_0 ) || !var_0.size )
        var_0 = getentarray( "ball_pickup", "targetname" );

    if ( level._id_CB1D > 1 )
        var_0 = _id_E028( var_0 );

    return var_0;
}

_id_68D4( var_0 )
{
    if ( isdefined( var_0 ) )
        var_1 = var_0.origin;
    else if ( level._id_48BE )
        var_1 = level.players[0].origin + ( 0, 0, 30 );
    else
        var_1 = level._id_4540;

    return var_1;
}

_id_20E3( var_0 )
{
    var_1 = 30;
    var_2 = spawnstruct();
    var_2.origin = var_0;
    var_3 = var_0;
    var_2 _id_20F7();
    var_2.origin = var_2._id_718A + ( 0, 0, var_1 );
    var_2._id_7D63 = 0;

    if ( level.mapname == "mp_desert" )
        var_3 = var_2._id_718A;

    if ( level.mapname == "mp_divide" )
        var_3 = var_2._id_718A;

    if ( scripts\mp\utility\game::getgametype() == "tdef" )
        level._id_216B[level._id_216B.size] = _id_3F76( var_3 );

    level._id_212E[level._id_212E.size] = var_2;
}

_id_20F7( var_0 )
{
    var_1 = self.origin + ( 0, 0, 32 );
    var_2 = self.origin + ( 0, 0, -1000 );
    var_3 = scripts\engine\trace::_id_3EC3( 1, 1, 1, 1, 0, 1, 1 );
    var_4 = [];
    var_5 = scripts\engine\trace::ray_trace( var_1, var_2, var_4, var_3 );
    self._id_718A = var_5["position"];
    return var_5["fraction"] != 0 && var_5["fraction"] != 1;
}

_id_3F76( var_0 )
{
    var_1 = spawn( "script_model", var_0 );
    var_1 setmodel( "ctf_game_flag_base" );
    var_1 _meth_85A2();
    var_1._id_228F = var_0;
    return var_1;
}

_id_DC85( var_0 )
{
    if ( isdefined( var_0._id_0B39[0] ) )
        var_0._id_0B39[0] delete();

    var_1 = undefined;
    var_2 = var_0.team;
    var_3 = var_0 _meth_81D2();

    if ( var_3 )
        var_2 = var_0 _meth_8154();
    else if ( var_2 == "spectator" )
        var_2 = "allies";

    var_4 = _func_0208( level._effect["ball_base_glow"], self._id_228F, var_0 );
    var_4 _meth_8321();
    var_0._id_0B39[0] = var_4;
    triggerfx( var_4 );
}

_id_212D( var_0, var_1 )
{
    if ( !isdefined( var_0 ) )
        var_0 = 0;

    if ( isdefined( var_1 ) )
        var_2 = spawn( "script_model", var_1 );
    else
        var_2 = level._id_212E[level._id_218A.size];

    var_3 = spawn( "script_model", var_2.origin );
    var_3 _meth_85A2();

    if ( scripts\mp\utility\game::getgametype() == "ball" || getdvarint( "scr_uplink_create_ball" ) == 1 )
    {
        var_3 setmodel( "offhand_wm_emp" );
        var_3 setnodeploy( 1 );
        level._id_2193 = makeweapon( "iw7_uplinkball_mp" );
        level._id_2185 = 1000000;
    }
    else
    {
        var_3 setmodel( "offhand_wm_emp" );
        var_3 setnodeploy( 1 );
        level._id_2193 = makeweapon( "iw7_tdefball_mp" );
        level._id_2185 = 250000;
    }

    var_4 = 32;
    var_5 = undefined;

    if ( isdefined( level._id_2134 ) && level._id_2134.size > 0 )
    {
        var_5 = level._id_2134[var_0];
        var_5.origin = var_3.origin;
    }
    else
        var_5 = spawn( "trigger_radius", var_3.origin - ( 0, 0, var_4 / 2 ), 0, var_4, var_4 );

    var_5 _meth_80DB();
    var_5 linkto( var_3 );
    var_5._id_A509 = 1;
    var_5._id_94FD = 1;
    var_5._id_22FB = var_5.origin;
    var_5._id_A509 = 1;
    var_6 = [ var_3 ];
    var_7 = _id_07AD::_id_3F86( "any", var_5, var_6, ( 0, 0, 32 ) );
    var_7._id_A8D2 = 1;
    var_7 _id_07AD::_id_1574( "any" );
    var_7 _id_2165();
    var_7._id_15BA = 0;
    var_7._id_32D0 = level._id_2193;
    var_7._id_8CAB = 0;
    var_7._id_1042B = ( 0, 0, 30 );
    var_7._id_31E1 = ::_id_20E7;
    var_7._id_AB3A = ::_id_210F;
    var_7._id_D52A = ::_id_212A;
    var_7._id_AB75 = ::_id_2112;
    var_7._id_32D1 = ::_id_2114;
    var_7._id_7D50 = 0;
    var_7._id_8F91 = 0;
    var_7._id_AE74 = 0;
    var_7._id_C57B = 1;
    var_7._id_8F92 = "none";
    var_7._id_216F = level._id_218A.size;
    var_7._id_B71D = undefined;
    var_7._id_B71C = undefined;
    var_7._id_AEA1 = undefined;
    var_7._id_AEA0 = undefined;
    var_7._id_1042E[0] _meth_85A8( 1 );

    if ( isdefined( level._id_DC9D ) )
    {
        switch ( level._id_DC9D )
        {
            case 0:
                var_7 _id_07AD::_id_D8D5( "friendly" );
                var_7._id_A8F9 = 0;
                var_7._id_A8F8 = 1;
                var_7._id_A8FF = 60.0;
                break;
            case 1:
                var_7 _id_07AD::_id_D8D5( "any" );
                var_7._id_A8F9 = 0;
                var_7._id_A8F8 = 0;
                var_7._id_A8FF = 0.05;
                break;
            case 2:
                var_7 _id_07AD::_id_D8D5( "any" );
                var_7._id_A8F9 = 0;
                var_7._id_A8F8 = 1;
                var_7._id_A8FF = 1.0;
                break;
            case 3:
                var_7 _id_07AD::_id_D8D5( "any" );
                var_7._id_A8F9 = 0;
                var_7._id_A8F8 = 1;
                var_7._id_A8FF = 1.5;
                break;
            case 4:
                var_7 _id_07AD::_id_D8D5( "any" );
                var_7._id_A8F9 = 0;
                var_7._id_A8F8 = 1;
                var_7._id_A8FF = 2.0;
                break;
            case 5:
                var_7 _id_07AD::_id_D8D5( "any" );
                var_7._id_A8F9 = 0;
                var_7._id_A8F8 = 1;
                var_7._id_A8FF = 3.0;
                break;
            case 6:
                var_7 _id_07AD::_id_D8D5( "any" );
                var_7._id_A8F9 = 0;
                var_7._id_A8F8 = 1;
                var_7._id_A8FF = 4.0;
                break;
        }
    }
    else
    {
        var_7 _id_07AD::_id_D8D5( "any" );
        var_7._id_A8F9 = 0;
        var_7._id_A8F8 = 1;
        var_7._id_A8FF = 3.0;
    }

    var_7 _id_20E4( var_2 );
    level._id_218A[level._id_218A.size] = var_7;

    if ( scripts\mp\utility\game::getgametype() == "tdef" )
        level._id_218A[0] thread _id_E6B7();

    if ( !istrue( level._id_48BE ) )
        var_7 thread _id_20F9( 1, 1 );

    var_7 thread _id_210A();
    var_8 = [ "physicscontents_clipshot", "physicscontents_missileclip", "physicscontents_vehicle", "physicscontents_characterproxy", "physicscontents_glass", "physicscontents_itemclip" ];
    var_9 = physics_createcontents( var_8 );
    level._id_2186 = var_9;
    level._id_218F = 10;

    if ( scripts\mp\utility\game::getgametype() == "tdef" )
        level._id_218F = 20;
}

_id_20E7( var_0 )
{
    if ( isdefined( self._id_504E ) && self._id_504E >= gettime() )
        return 0;

    if ( isplayer( var_0 ) )
    {
        if ( !var_0 scripts\common\utility::_id_8702() )
            return 0;

        if ( isdefined( var_0._id_9A4F ) && var_0._id_9A4F )
            return 0;

        if ( istrue( var_0._id_878D ) )
            return 0;

        if ( !_id_FF2D( var_0 ) )
            return 0;

        var_1 = var_0 getcurrentweapon();

        if ( isdefined( var_1 ) )
        {
            if ( !_id_FF2C( var_1 ) )
                return 0;
        }

        var_2 = var_0._id_33CA;

        if ( isdefined( var_2 ) && var_0 isswitchingweapon() )
        {
            if ( !_id_FF2C( var_2 ) )
                return 0;
        }

        if ( var_0 scripts\cp_mp\utility\inventory_utility::_id_873B() )
        {
            var_2 = var_0 scripts\cp_mp\utility\inventory_utility::_id_6987();

            if ( !_id_FF2C( var_2 ) )
                return 0;
        }

        if ( var_0 scripts\mp\utility\player::_id_8AB5() )
            return 0;

        if ( var_0 _id_B546() )
            return 0;
    }
    else
        return 0;

    return 1;
}

_id_210F( var_0, var_1 )
{
    var_0 notify( "obj_picked_up" );
    var_0 thread _id_34ED();
    var_2 = 0;

    if ( level._id_2188 )
    {
        if ( _id_6F81( var_0 ) )
            var_0 thread _id_0A76::_id_6FE6( "ball_grab" );

        level._id_2187 = gettime();
        level._id_2188 = 0;

        if ( isdefined( level._id_BA02 ) && level._id_BA02 == 1 && istrue( level._id_BA03 ) )
            var_2 = 1;

        var_0 notify( "ball_grab" );
    }

    if ( isdefined( level._id_BA02 ) && level._id_BA02 == 2 && istrue( level._id_BA03 ) && isdefined( self._id_8F90 ) && self._id_8F90 != var_0 )
        var_2 = 1;

    if ( scripts\mp\utility\game::getgametype() == "tdef" )
    {
        var_0 scripts\mp\gametypes\tdef::_id_6D04();
        level thread scripts\mp\gametypes\tdef::_id_1F9C( var_0.team );

        if ( !level._id_F260 )
            level scripts\mp\gamelogic::pausetimer();
    }

    if ( istrue( level._id_BA02 ) )
        level _id_FD64( var_0.team, 0, 0, var_2 );

    level._id_FED2 = 0;
    level._id_39F4 = undefined;
    level._id_39F6 = undefined;
    var_3 = self._id_1042E[0] _meth_8151();

    if ( isdefined( var_3 ) )
        self._id_1042E[0] unlink();

    if ( !istrue( level._id_48BE ) )
        var_0 scripts\mp\utility\perk::_id_6FA5( "specialty_ballcarrier" );

    var_0._id_20E8 = self;
    var_0._id_A850 = 1;
    self._id_32AF scripts\mp\utility\perk::_id_6FA5( "specialty_sprintfire" );
    self._id_32AF._id_7577 = 1;

    if ( !istrue( level._id_48BE ) )
        var_0 _id_07C1::_id_D5D5( var_0, level._id_32B0 );

    if ( !istrue( level._id_48BE ) )
        thread _id_2123( var_0.team, "mp_uplink_ball_pickedup_friendly", "mp_uplink_ball_pickedup_enemy" );

    var_0 scripts\common\utility::_id_1562( 0 );
    var_0 scripts\mp\equipment::_id_1512( 0, "obj_ball" );
    self._id_1042E[0] physicslaunchserver( self._id_1042E[0].origin, ( 0, 0, 0 ) );
    self._id_1042E[0] _meth_8544();
    self._id_1042E[0] scripts\mp\movers::_id_A65F();
    self._id_AE74 = 0;
    self._id_1042E[0] _id_E89A();
    self._id_1042E[0] show();
    self._id_1042E[0] hide( 1 );
    self._id_1042E[0] linkto( var_0, "j_wrist_ri", ( 0, 0, 0 ), var_0.angles );
    self._id_1042E[0] setscriptablepartstate( "uplink_drone_hide", "hide", 0 );
    self._id_047A scripts\mp\movers::_id_E8A0();
    self._id_417C._id_7D63 = 0;
    var_4 = 0;

    if ( isdefined( self._id_BD8D ) )
    {
        var_4 = 1;
        self._id_BD8D delete();
    }

    var_5 = var_0.team;
    var_6 = scripts\mp\utility\game::_id_6BC3( var_0.team )[0];
    self._id_1042E[0] setotherent( var_0 );

    if ( var_4 )
    {
        if ( self._id_8F92 == var_0.team )
        {
            if ( !istrue( level._id_48BE ) )
                _id_0A64::_id_E772( "pass_complete", var_5 );

            var_0._id_AEA2 = gettime();
            var_0._id_AE9F = self._id_8F90;
        }
        else
        {
            if ( !istrue( level._id_48BE ) )
                _id_0A64::_id_E772( "pass_intercepted", var_5 );

            var_0 thread _id_0788::_id_6F9C( "mode_uplink_intercept" );

            if ( isplayer( var_0 ) )
                var_0 thread scripts\common\utility::_id_F737( level._id_9B9C, "pickup_interception", var_0.origin );
        }
    }
    else
    {
        if ( !istrue( level._id_48BE ) && self._id_8F92 != var_0.team )
        {
            _id_0A64::_id_E772( "ally_own_drone", var_5 );
            _id_0A64::_id_E772( "enemy_own_drone", var_6 );
        }

        if ( isplayer( var_0 ) )
            var_0 thread scripts\common\utility::_id_F737( level._id_9B9C, "pickup", var_0.origin );
    }

    if ( !istrue( level._id_48BE ) )
        _id_20FB();

    self._id_8F91 = 0;
    self._id_8F90 = var_0;
    self._id_8F92 = var_0.team;
    self._id_AD9B = var_0.team;
    _id_2164( self._id_AD9B );
    var_0 setweaponammoclip( level._id_2193, 1 );

    if ( level._id_39F9 )
        var_0 _meth_80CB( 1 );

    var_0 thread _id_B606( self );

    if ( !istrue( level._id_48BE ) )
        scripts\mp\gamelogic::_id_D580( var_0, 1 );

    self notify( "physics_timeout" );
}

_id_34ED()
{
    self endon( "death_or_disconnect" );
    self endon( "drop_object" );
    waitframe();

    if ( isdefined( self._id_62D2 ) && self _meth_84B6( self._id_62D2 ) )
        self _meth_8493( self._id_62D2, 0.05, 1 );
}

_id_48AA()
{

}

_id_6F81( var_0 )
{
    if ( scripts\mp\utility\game::getgametype() == "tdef" )
        var_1 = 15000;
    else
        var_1 = 10000;

    var_2 = var_0 _id_FC16();

    if ( var_2 )
        return 0;

    if ( isdefined( self._id_8F90 ) && var_0.team == self._id_8F90.team && gettime() < level._id_2187 + var_1 )
        return 0;

    return 1;
}

_id_FC16()
{
    if ( !isdefined( self._id_29C8 ) )
    {
        self._id_A774 = 0;
        self._id_29C8 = 0;
    }

    self._id_A774++;

    if ( scripts\mp\utility\game::_id_6B40() < 1 )
        return 0;

    self._id_29C8 = self._id_A774 / scripts\mp\utility\game::_id_6B40();

    if ( self._id_29C8 < 4 )
        return 0;
    else
        return 1;
}

_id_2123( var_0, var_1, var_2 )
{
    var_3 = scripts\mp\utility\game::_id_6BC3( var_0 )[0];

    foreach ( var_5 in level.players )
    {
        if ( var_5.team == var_0 )
        {
            var_5 playlocalsound( var_1 );
            continue;
        }

        if ( var_5.team == var_3 )
            var_5 playlocalsound( var_2 );
    }
}

_id_212A( var_0, var_1, var_2, var_3 )
{
    if ( !isdefined( var_0 ) )
        var_0 = 0;

    var_4 = 0;
    self._id_89E5 = 1;
    self._id_504E = gettime();
    self notify( "dropped" );
    var_5 = ( 0, 0, 0 );
    var_6 = self._id_32AF;

    if ( isdefined( var_6 ) && var_6.team != "spectator" )
    {
        var_7 = var_6.origin;
        var_5 = var_6.angles;
        var_6 notify( "ball_dropped" );
    }
    else if ( isdefined( var_1 ) )
        var_7 = var_1;
    else
        var_7 = self._id_CADA;

    var_7 = var_7 + ( 0, 0, 40 );

    if ( isdefined( self._id_BD8D ) )
        self._id_BD8D delete();

    for ( var_8 = 0; var_8 < self._id_1042E.size; var_8++ )
    {
        self._id_1042E[var_8].origin = var_7;
        self._id_1042E[var_8].angles = var_5;
        self._id_1042E[var_8] show();
        var_9 = self._id_1042E[var_8] _meth_8151();

        if ( isdefined( var_9 ) )
            self._id_1042E[var_8] unlink();

        self._id_1042E[var_8] setscriptablepartstate( "uplink_drone_hide", "show", 0 );
    }

    if ( istrue( var_3 ) || istrue( var_2 ) )
        var_4 = 1;

    _id_20E9( var_4 );

    if ( !isdefined( level._id_CBF8 ) )
        level._id_CBF8 = 0;

    if ( level._id_CBF8 > 0 )
        self._id_047A.origin = self._id_047A.origin - ( 0, 0, 10000 );
    else
        self._id_047A.origin = var_7;

    _id_20F3();
    self._id_411F = self._id_047A.origin;

    if ( !istrue( level._id_48BE ) )
        thread _id_20F9( 0 );

    self._id_AD9B = "any";
    _id_2165();
    _id_07AD::_id_3907();

    if ( isdefined( var_6 ) )
        var_6 _id_B607();

    _id_07AD::_id_FC38();
    self._id_89E5 = 0;

    if ( !var_0 )
    {
        var_10 = self._id_8F92;
        var_11 = scripts\mp\utility\game::_id_6BC3( var_10 )[0];

        if ( !istrue( level._id_48BE ) && !isdefined( var_1 ) && !istrue( var_2 ) )
        {
            _id_0A64::_id_E772( "ally_drop_drone", var_10 );
            _id_0A64::_id_E772( "enemy_drop_drone", var_11 );
        }

        var_12 = ( 0, var_5[1], 0 );
        var_13 = anglestoforward( var_12 );

        if ( isdefined( var_1 ) )
            var_14 = var_13 * 20 + ( 0, 0, 80 );
        else
            var_14 = var_13 * 200 + ( 0, 0, 80 );

        _id_211C( var_14 );
    }

    var_15 = spawnstruct();
    var_15._id_32C6 = self;
    var_15._id_43D6 = ::_id_2113;
    self._id_047A thread scripts\mp\movers::_id_73E7( var_15 );

    if ( level._id_F260 )
        level scripts\mp\gamelogic::resumetimer();

    return 1;
}

_id_20E9( var_0 )
{
    if ( isdefined( self._id_32AF ) )
    {
        if ( scripts\mp\utility\game::getgametype() == "tdef" )
            self._id_32AF scripts\mp\gametypes\tdef::_id_6D04();

        self._id_32AF._id_216D = undefined;
        self._id_32AF._id_A5A5 = gettime() + 500;
        self._id_32AF _id_B3DE();
        self._id_32AF notify( "cancel_update_pass_target" );
        self._id_32AF._id_20E8 = undefined;

        if ( !istrue( level._id_48BE ) )
        {
            self._id_32AF scripts\mp\utility\perk::removeperk( "specialty_ballcarrier" );
            self._id_32AF _id_07C1::_id_943E( self._id_32AF );
        }

        if ( self._id_32AF._id_7577 )
            self._id_32AF scripts\mp\utility\perk::removeperk( "specialty_sprintfire" );

        self._id_32AF._id_7577 = 0;

        if ( level._id_39F9 )
            self._id_32AF _meth_80CB( 0 );

        self._id_32AF scripts\common\utility::_id_1562( 1 );

        if ( istrue( var_0 ) )
            self._id_32AF scripts\mp\equipment::_id_1512( 1, "obj_ball" );

        self._id_32AF _meth_8543( 0 );
        self._id_32AF._id_A850 = 0;
        self._id_1042E[0] setotherent( undefined );
    }
}

_id_2112()
{
    _id_20E4( level._id_212E[self._id_216F] );
    _id_2126();
    var_0 = self._id_1042E[0];
    var_0 scripts\mp\movers::_id_A65F();
    var_1 = var_0 _meth_8151();

    if ( isdefined( var_1 ) )
        var_0 unlink();

    self._id_1042E[0] _id_E89A();
    var_0 physicslaunchserver( var_0.origin, ( 0, 0, 0 ) );
    var_0 _meth_8544();
    _id_20F3();

    if ( isdefined( self._id_BD8D ) )
        self._id_BD8D delete();

    var_2 = "none";
    var_3 = self._id_8F92;

    if ( isdefined( var_3 ) )
        var_2 = scripts\mp\utility\game::_id_6BC3( var_3 )[0];

    self._id_8F92 = "none";
    _id_20E9( 1 );
    self._id_047A scripts\mp\movers::_id_E8A0();
    _id_2163();

    if ( scripts\mp\utility\game::getgametype() != "tdef" )
    {
        _id_07AD::_id_D678( var_0._id_22FB + ( 0, 0, 4000 ), ( 0, 0, 0 ) );
        var_0 moveto( var_0._id_22FB, 3, 0, 3 );
        var_0 _meth_82A7( ( 0, 720, 0 ), 3, 0, 3 );
    }
    else
    {
        if ( !level._id_F260 )
            level scripts\mp\gamelogic::pausetimer();

        var_0 hide( 1 );
        self._id_1042E[0] setscriptablepartstate( "uplink_drone_hide", "hide", 0 );
        thread _id_10821( var_0 );
    }

    if ( !istrue( level._id_48BE ) )
        playsoundatpos( var_0._id_22FB, "mp_uplink_ball_reset" );

    if ( !self._id_8F91 && isdefined( var_3 ) && isdefined( var_2 ) )
    {
        if ( !istrue( level._id_48BE ) && var_3 != "none" && !istrue( level._id_609B ) )
        {
            _id_0A64::_id_E772( "drone_reset", var_3 );
            _id_0A64::_id_E772( "drone_reset", var_2 );
        }

        if ( isdefined( self._id_8F90 ) )
        {

        }
    }

    self._id_AD9B = "any";

    if ( scripts\mp\utility\game::getgametype() == "ball" || level._id_48BE )
        thread _id_20F5( 3 );

    if ( !istrue( level._id_48BE ) )
        thread _id_20F4( var_0, 3 );

    thread scripts\common\utility::_id_F737( level._id_9B9C, "obj_return", var_0._id_22FB );
}

_id_20ED()
{
    self._id_1042E[0] notsolid();
}

_id_2114()
{
    self endon( "disconnect" );
    thread _id_2118();
    thread _id_212C();
    thread _id_2168();
    self._id_32C6 waittill( "dropped" );
}

_id_2118()
{
    level endon( "game_ended" );
    self endon( "death_or_disconnect" );
    self endon( "drop_object" );

    for (;;)
    {
        self waittill( "ball_pass", var_0 );

        if ( var_0 != level._id_2193 )
            continue;

        if ( !isdefined( self._id_AE81 ) )
        {
            self iprintlnbold( "No Pass Target" );
            continue;
        }

        self._id_32C6._id_AE74 = 1;
        break;
    }

    if ( isdefined( self._id_32C6 ) )
    {
        thread _id_2115();
        var_1 = self._id_AE81;
        var_2 = self._id_AE81.origin;
        wait 0.15;

        if ( isdefined( self._id_AE81 ) )
            var_1 = self._id_AE81;

        self._id_32C6 thread _id_2116( self, var_1, var_2 );
    }
}

_id_212C()
{
    level endon( "game_ended" );
    self endon( "death_or_disconnect" );
    self endon( "drop_object" );

    if ( scripts\mp\utility\game::getgametype() != "tdef" )
    {
        var_0 = getdvarfloat( "scr_ball_shoot_extra_pitch", 0 );
        var_1 = getdvarfloat( "scr_ball_shoot_force", 825 );
    }
    else
    {
        var_0 = getdvarfloat( "scr_tdef_shoot_extra_pitch", -3 );
        var_1 = getdvarfloat( "scr_tdef_shoot_force", 450 );
    }

    for (;;)
    {
        self waittill( "weapon_fired", var_2 );

        if ( var_2 != level._id_2193 )
            continue;

        self setweaponammoclip( var_2, 0 );
        break;
    }

    if ( isdefined( self._id_32C6 ) )
    {
        thread _id_07C5::_id_9780( "pass", self.origin );

        if ( !istrue( level._id_48BE ) )
            self playsound( "mp_uplink_ball_pass" );

        wait 0.15;

        if ( self issprintsliding() )
        {
            var_0 = -12;

            if ( scripts\mp\utility\game::getgametype() == "tdef" )
                var_1 = var_1 + 200;
        }

        var_3 = self getplayerangles();
        var_3 = var_3 + ( var_0, 0, 0 );
        var_3 = ( clamp( var_3[0], -85, 85 ), var_3[1], var_3[2] );
        var_4 = anglestoforward( var_3 );
        thread _id_2115();
        thread _id_20EC( self._id_32C6 );
        self._id_32C6 _id_20F0();
        self._id_32C6 thread _id_211D( var_4 * var_1, self );
    }
}

_id_2168()
{
    level endon( "game_ended" );
    self endon( "death_or_disconnect" );
    self endon( "drop_object" );
    thread _id_EB10();
    var_0 = level._id_2193;

    for (;;)
    {
        if ( var_0 == self getcurrentweapon() )
            break;

        self waittill( "weapon_change" );
    }

    for (;;)
    {
        self waittill( "weapon_change", var_1 );

        if ( isdefined( var_1 ) && scripts\mp\utility\weapon::_id_8A63( var_1.basename ) )
            break;
    }

    var_2 = self getplayerangles();
    var_2 = ( clamp( var_2[0], -85, 85 ), _func_0438( var_2[1] + 20 ), var_2[2] );
    var_3 = anglestoforward( var_2 );
    var_4 = 90;
    self._id_32C6 thread _id_211D( var_3 * var_4, self, 1 );
}

_id_EB10()
{
    self endon( "death_or_disconnect" );
    self endon( "drop_object" );
    self endon( "unsetBallCarrier" );
    self waittill( "super_started" );
    var_0 = self._id_EB06;

    switch ( var_0._id_E768._id_C17B )
    {
        case "super_chargemode":
            _id_20F6();
            break;
        case "super_rewind":
            scripts\engine\utility::waittill_any_2( "teleport_success", "rewind_success" );
            _id_20F6();
            break;
    }
}

_id_20F6()
{
    var_0 = self getplayerangles();
    var_0 = ( clamp( var_0[0], -85, 85 ), _func_0438( var_0[1] + 20 ), var_0[2] );
    var_1 = anglestoforward( var_0 );
    var_2 = 90;
    self._id_32C6 thread _id_211D( var_1 * var_2, self, 1 );
}

_id_2115()
{
    self endon( "death_or_disconnect" );
    self._id_AE7E = 1;
    self allowmelee( 0 );

    while ( level._id_2193 == self getcurrentweapon() )
        waitframe();

    self allowmelee( 1 );
    self._id_AE7E = 0;
    scripts\mp\equipment::_id_1512( 1, "obj_ball" );
}

_id_211D( var_0, var_1, var_2 )
{
    _id_212A( 1, undefined, 0, var_2 );
    _id_211C( var_0, var_1 );
}

_id_2116( var_0, var_1, var_2 )
{
    _id_212A( 1 );

    if ( isdefined( var_1 ) )
        var_2 = var_1.origin;

    var_3 = var_0 _id_6BF3();
    var_4 = var_0 _id_6BF2();

    if ( !_id_FF4D( self, var_0, var_1 ) )
    {
        var_3 = self._id_90A9;
        var_4 = self._id_90A8;
    }

    var_5 = var_4 * 30;
    var_6 = var_4 * 60;
    var_7 = var_3 + var_5;
    var_8 = var_1 _id_6DA4();
    var_9 = scripts\engine\trace::_id_E406( var_7, var_8, level._id_218F, var_0, level._id_2186, 0 );
    var_10 = 1.0;

    if ( var_9["fraction"] < 1 )
    {
        if ( var_9["hittype"] == "hittype_entity" && isdefined( var_9["entity"] ) && isplayer( var_9["entity"] ) )
            var_10 = max( 0.1, 0.7 * var_9["fraction"] );
        else
            var_10 = 0.7 * var_9["fraction"];

        _id_07AD::_id_D678( var_7 + var_5 * var_10, self._id_1042E[0].angles );
    }
    else
        _id_07AD::_id_D678( var_9["position"], self._id_1042E[0].angles );

    if ( isdefined( var_1 ) )
    {
        self._id_BD8D = scripts\cp_mp\utility\weapon_utility::_magicbullet( makeweapon( "uplinkball_tracking_mp" ), var_7 + var_6 * var_10, var_8, var_0 );
        self._id_BD8D missile_settargetent( var_1, var_1 _id_6DA3() );
    }

    self._id_047A.origin = self._id_047A.origin - ( 0, 0, 10000 );
    var_1 thread _id_116B( self._id_BD8D );
    self._id_1042E[0] linkto( self._id_BD8D );
    _id_20F3();
    _id_20F0();
    _id_20ED();
    level._id_39F4 = self._id_1042E[0];
    thread _id_2111();
    thread _id_2110();
    thread _id_210E();
    thread _id_2132();
    thread _id_2131();
    thread _id_2133( var_1 );

    if ( scripts\mp\utility\game::getgametype() == "ball" )
        thread scripts\mp\gametypes\ball::_id_2117();
}

_id_B606( var_0 )
{
    self endon( "disconnect" );
    self endon( "cancel_update_pass_target" );
    _id_B607();
    childthread _id_B518();

    for (;;)
    {
        var_1 = undefined;

        if ( !self isonladder() )
        {
            var_2 = [];

            foreach ( var_4 in level.players )
            {
                if ( !isdefined( var_4.team ) )
                    continue;

                if ( var_4.team != self.team )
                    continue;

                if ( !scripts\mp\utility\player::isreallyalive( var_4 ) )
                    continue;

                if ( !var_0 _id_20E7( var_4 ) )
                    continue;

                if ( _id_FF4D( var_0, self, var_4 ) )
                    var_2[var_2.size] = var_4;
            }

            if ( isdefined( var_2 ) && var_2.size > 0 )
            {
                var_2 = _id_0A78::_id_BEE9( var_2, ::_id_3AD1 );
                var_6 = self geteye();

                foreach ( var_4 in var_2 )
                {
                    var_8 = var_4 _id_6DA4();

                    if ( _func_01FD( var_6, var_8, 0, self, var_4 ) )
                    {
                        var_1 = var_4;
                        break;
                    }
                }
            }
        }

        _id_B5B8( var_1 );
        waitframe();
    }
}

_id_FF4D( var_0, var_1, var_2 )
{
    var_3 = 0.85;
    var_4 = var_1 _id_6BF3();
    var_5 = var_1 _id_6BF2();
    var_6 = var_2 _id_6DA4();
    var_7 = distancesquared( var_6, var_4 );

    if ( var_7 > level._id_2185 )
        return 0;

    var_8 = vectornormalize( var_6 - var_4 );
    var_9 = vectordot( var_5, var_8 );

    if ( var_9 > var_3 )
    {
        var_10 = var_5 * 30;
        var_11 = var_4 + var_10;
        var_12 = scripts\engine\trace::_id_E406( var_11, var_6, level._id_218F, var_1, level._id_2186, 0 );

        if ( isdefined( var_12["entity"] ) && isplayer( var_12["entity"] ) || var_12["fraction"] > 0.8 )
        {
            var_2._id_AE76 = var_9;
            var_0._id_90A9 = var_4;
            var_0._id_90A8 = var_5;
            return 1;
        }
    }

    return 0;
}

_id_B607()
{
    if ( !isdefined( self ) )
        return;

    if ( !isdefined( self._id_32C6 ) )
        return;

    if ( isdefined( self._id_32C6._id_AEA1 ) && isdefined( self._id_32C6._id_AEA0 ) )
    {
        scripts\mp\utility\outline::outlinedisable( self._id_32C6._id_AEA1, self._id_32C6._id_AEA0 );
        self._id_32C6._id_AEA1 = undefined;
        self._id_32C6._id_AEA0 = undefined;
    }

    if ( isdefined( self._id_32C6._id_B71D ) && isdefined( self._id_32C6._id_B71C ) )
    {
        scripts\mp\utility\outline::outlinedisable( self._id_32C6._id_B71D, self._id_32C6._id_B71C );
        self._id_32C6._id_B71D = undefined;
        self._id_32C6._id_B71C = undefined;
    }

    if ( self._id_32C6._id_89E5 )
        return;

    var_0 = [];
    var_1 = [];
    var_2 = scripts\mp\utility\game::_id_6BC3( self.team )[0];
    var_3 = undefined;
    var_4 = undefined;

    foreach ( var_6 in level.players )
    {
        if ( var_6 == self )
            continue;

        if ( var_6.team == self.team )
        {
            var_0[var_0.size] = var_6;
            continue;
        }

        if ( var_6.team == var_2 )
            var_1[var_1.size] = var_6;
    }

    foreach ( var_6 in var_0 )
        var_9 = isdefined( self._id_AE81 ) && self._id_AE81 == var_6;

    if ( isdefined( self._id_AE81 ) )
        var_3 = scripts\mp\utility\outline::outlineenableforplayer( self._id_AE81, self, "outline_depth_cyan", "level_script" );

    self._id_32C6._id_AEA1 = var_3;
    self._id_32C6._id_AEA0 = self._id_AE81;

    if ( scripts\mp\utility\game::getgametype() == "tdef" && var_0.size > 0 )
        var_4 = scripts\mp\utility\outline::_id_ACBF( self, self.team, "outlinefill_nodepth_cyan", "level_script" );

    self._id_32C6._id_B71D = var_4;
    self._id_32C6._id_B71C = self;
}

_id_116B( var_0 )
{
    var_1 = self;
    var_0 endon( "pass_end" );

    while ( isdefined( var_1 ) && isdefined( var_0 ) )
    {
        var_0 missile_settargetent( var_1, var_1 _id_6DA3() );
        waitframe();
    }
}

_id_3AD1( var_0, var_1 )
{
    return var_0._id_AE76 >= var_1._id_AE76;
}

_id_B518()
{

}

_id_B5B8( var_0 )
{
    var_1 = 80;
    var_2 = 0;

    if ( isdefined( var_0 ) )
    {
        switch ( var_0 getstance() )
        {
            case "crouch":
                var_1 = 60;
                break;
            case "prone":
                var_1 = 35;
                break;
        }

        if ( !isdefined( self._id_AE7C ) || self._id_AE7C != var_1 )
        {
            var_2 = 1;
            self._id_AE7C = var_1;
        }
    }

    var_3 = ( 0, 0, var_1 );

    if ( isdefined( self._id_AE81 ) && isdefined( var_0 ) && self._id_AE81 == var_0 )
    {
        if ( var_2 )
            self._id_AE7B = var_0 thread _id_0766::_id_D58E( self, "waypoint_ball_pass", var_1, 0, undefined, undefined, 0.05 );

        return;
    }

    if ( !isdefined( self._id_AE81 ) && !isdefined( var_0 ) )
        return;

    _id_B3DE();

    if ( isdefined( var_0 ) )
    {
        self._id_AE7B = var_0 thread _id_0766::_id_D58E( self, "waypoint_ball_pass", var_1, 0, undefined, undefined, 0.05 );
        self._id_AE81 = var_0;
        var_4 = [];

        foreach ( var_6 in level.players )
        {
            if ( var_6.team == self.team && var_6 != self && var_6 != var_0 )
                var_4[var_4.size] = var_6;
        }

        self _meth_8543( 1 );
    }

    _id_B607();
}

_id_B3DE()
{
    if ( isdefined( self._id_AE7B ) )
        self._id_AE7B destroy();

    var_0 = [];

    foreach ( var_2 in level.players )
    {
        if ( var_2.team == self.team && var_2 != self )
            var_0[var_0.size] = var_2;
    }

    self._id_AE81 = undefined;
    self _meth_8543( 0 );
    _id_B607();
}

_id_B546()
{
    return isdefined( self._id_A5A5 ) && self._id_A5A5 > gettime() || isdefined( self._id_20E8 );
}

_id_FF2D( var_0 )
{
    if ( !isdefined( var_0._id_EB06 ) )
        return 1;

    if ( !isdefined( var_0._id_EB06._id_88BA ) || !var_0._id_EB06._id_88BA )
        return 1;

    return 1;
}

_id_FF2C( var_0 )
{
    var_1 = undefined;

    if ( isweapon( var_0 ) )
    {
        if ( isnullweapon( var_0 ) )
            return 0;

        if ( var_0 == level._id_2193 )
            return 0;

        var_1 = var_0.basename;
    }

    if ( _func_0120( var_0 ) )
    {
        if ( var_0 == "none" )
            return 0;

        if ( var_0 == level._id_2193.basename )
            return 0;

        var_1 = var_0;
    }

    if ( _id_0A6F::_id_89E1( var_1 ) )
        return 0;

    if ( scripts\mp\utility\weapon::_id_88DC( var_0 ) )
        return 0;

    return 1;
}

_id_210E()
{
    self._id_1042E[0] endon( "pass_end" );
    level waittill( "host_migration_begin" );

    if ( isdefined( self._id_BD8D ) )
    {
        if ( !isdefined( self._id_AE81 ) && !isdefined( self._id_32AF ) && !self._id_7D50 )
        {
            if ( self._id_1042E[0].origin != self._id_1042E[0]._id_22FB + ( 0, 0, 4000 ) )
            {
                _id_2126();

                if ( !isdefined( self._id_900F ) )
                    self._id_900F = ( 0, 0, 1 );

                _id_211C( self._id_900F * 400 );
            }
        }
    }
}

_id_2132()
{
    self._id_1042E[0] endon( "pass_end" );
    self._id_BD8D endon( "projectile_impact_player" );
    self._id_BD8D endon( "death" );
    self._id_900F = undefined;
    var_0 = undefined;

    for (;;)
    {
        if ( isdefined( var_0 ) )
            self._id_900F = vectornormalize( self._id_BD8D.origin - var_0 );

        var_0 = self._id_BD8D.origin;
        waitframe();
    }
}

_id_2131()
{
    self._id_1042E[0] endon( "pass_end" );
    self._id_BD8D endon( "projectile_impact_player" );
    self._id_BD8D endon( "death" );
    var_0 = gettime();

    for ( var_1 = var_0; var_1 < var_0 + 2000; var_1 = gettime() )
        waitframe();

    self._id_BD8D delete();
}

_id_2133( var_0 )
{
    self._id_1042E[0] endon( "pass_end" );
    self._id_BD8D endon( "projectile_impact_player" );
    self._id_BD8D endon( "death" );

    for (;;)
    {
        if ( !isdefined( var_0 ) )
            break;

        if ( !scripts\mp\utility\player::isreallyalive( var_0 ) )
            break;

        waitframe();
    }

    self._id_BD8D delete();
}

_id_2110()
{
    self endon( "reset" );
    self._id_BD8D waittill( "death" );
    waittillframeend;
    self._id_047A.origin = self._id_411F;
    var_0 = self._id_1042E[0];

    if ( !isdefined( self._id_32AF ) && !self._id_7D50 )
    {
        if ( var_0.origin != var_0._id_22FB + ( 0, 0, 4000 ) )
        {
            _id_2126();

            if ( !isdefined( self._id_900F ) )
                self._id_900F = ( 0, 0, 1 );

            _id_211C( self._id_900F * 400 );
        }
    }

    _id_2126();
    var_0 notify( "pass_end" );
}

_id_2111()
{
    self._id_1042E[0] endon( "pass_end" );
    self._id_BD8D waittill( "projectile_impact_player", var_0 );
    self._id_047A.origin = self._id_1042E[0].origin;
    self._id_047A notify( "trigger", var_0 );
}

_id_211C( var_0, var_1 )
{
    var_2 = self._id_1042E[0];
    var_2._id_AC6B = undefined;
    var_3 = var_2.origin;
    var_4 = var_2;

    if ( isdefined( var_1 ) )
    {
        var_4 = var_1;
        var_3 = var_1 geteye();
        var_5 = anglestoright( var_0 );
        var_3 = var_3 + ( var_5[0], var_5[1], 0 ) * 7;

        if ( var_1 issprintsliding() )
            var_3 = var_3 + ( 0, 0, 10 );

        var_6 = var_3;
        var_7 = vectornormalize( var_0 ) * 80;
        var_8 = [ "physicscontents_clipshot", "physicscontents_missileclip", "physicscontents_vehicle", "physicscontents_characterproxy", "physicscontents_glass", "physicscontents_itemclip" ];
        var_9 = physics_createcontents( var_8 );
        var_10 = scripts\engine\trace::_id_E406( var_6, var_6 + var_7, 38, var_1, var_9 );

        if ( var_10["fraction"] < 1 )
        {
            var_11 = 0.7 * var_10["fraction"];
            _id_07AD::_id_D678( var_6 + var_7 * var_11, var_2.angles );
        }
        else
            _id_07AD::_id_D678( var_10["position"], var_2.angles );
    }

    self._id_1042E[0] physicslaunchserver( var_2.origin, var_0 );
    self._id_1042E[0] thread _id_0A67::_id_C1FB();
    self._id_1042E[0] physics_registerforcollisioncallback();
    _id_0A67::_id_C1FA( self._id_1042E[0], ::_id_2107 );
    self._id_1042E[0].origin = self._id_047A.origin;
    self._id_047A linkto( self._id_1042E[0] );
    level._id_39F4 = self._id_1042E[0];
    level._id_39F7 = var_4;
    level._id_39F6 = var_0;
    thread _id_211E();
    thread _id_211F( var_1 );
    thread _id_211A();

    if ( scripts\mp\utility\game::getgametype() == "ball" )
        thread scripts\mp\gametypes\ball::_id_2121();

    thread _id_2120( var_1 );
}

_id_2120( var_0 )
{
    var_1 = self._id_1042E[0];
    var_2 = self._id_047A;
    self._id_1042E[0] endon( "physics_finished" );
    self endon( "physics_timeout" );
    self endon( "pickup_object" );
    self endon( "reset" );
    self endon( "score_event" );

    for (;;)
    {
        var_2 waittill( "trigger", var_3 );

        if ( !isplayer( var_3 ) && !isagent( var_3 ) )
            continue;

        if ( isdefined( var_0 ) && var_0 == var_3 && var_3 _id_B546() )
            continue;

        if ( self._id_504E >= gettime() )
            continue;

        if ( var_1.origin == var_1._id_22FB + ( 0, 0, 4000 ) )
            continue;

        if ( !_id_20E7( var_3 ) )
        {
            if ( var_3 _id_B546() )
                continue;

            var_3._id_A5A5 = gettime() + 500;
            thread _id_211B();
        }
    }
}

_id_211B( var_0 )
{
    var_1 = self._id_1042E[0];
    var_2 = var_1 _meth_846D( 0 );
    var_3 = _func_029C( var_2 );

    if ( isdefined( var_0 ) && var_0 )
    {
        var_4 = length( var_3 ) * 0.4;
        thread _id_10C06();
    }
    else
        var_4 = length( var_3 ) / 10;

    var_5 = vectornormalize( var_3 );
    var_5 = ( -1, -1, -0.5 ) * var_5;
    var_1 physicslaunchserver( var_1.origin, ( 0, 0, 0 ) );
    var_1 _meth_8544();
    var_1 physicslaunchserver( var_1.origin, var_5 * var_4 );
    var_1._id_B03C = 1;
}

_id_B03A()
{
    self endon( "death" );

    for (;;)
    {
        self waittill( "projectile_impact", var_0, var_1, var_2, var_3 );
        var_4 = level._effect["ball_physics_impact"];

        if ( isdefined( var_3 ) && isdefined( level._effect["ball_physics_impact_" + var_3] ) )
            var_4 = level._effect["ball_physics_impact_" + var_3];

        if ( !istrue( level._id_48BE ) )
            playfx( var_4, var_0, var_1 );

        wait 0.3;
    }
}

_id_2107( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8 )
{
    var_9 = var_0 _meth_846D( 0 );
    var_10 = _func_029C( var_9 );
    var_11 = length( var_10 );

    if ( isdefined( var_0._id_B84A ) || var_11 < 70 )
        return;

    var_0 endon( "death" );
    var_0._id_B84A = 1;
    var_12 = "mp_uplink_ball_bounce";
    var_0 playsound( var_12 );
    var_13 = _func_0140( var_12 );
    wait 0.1;
    var_0._id_B84A = undefined;
}

_id_2127( var_0, var_1 )
{
    self._id_20F8 = 0;

    if ( istrue( level._id_5799 ) && istrue( var_0 ) )
        _id_48AA();

    if ( istrue( level._id_BA02 ) )
    {
        if ( istrue( level._id_2169 ) )
            level _id_FD64( "neutral", 0, 1 );
        else
            level _id_FD64( "neutral", 1, 1 );
    }

    level._id_39F4 = undefined;
    level._id_39F6 = undefined;
    level._id_2188 = 1;
    self._id_7D50 = 0;
    var_2 = self._id_1042E[0];
    var_2 physicslaunchserver( var_2.origin, ( 0, 0, 0 ) );
    var_2 _meth_8544();

    if ( !istrue( level._id_48BE ) )
    {
        playsoundatpos( var_2.origin, "mp_uplink_ball_out_of_bounds" );
        playfx( scripts\engine\utility::getfx( "ball_teleport" ), var_2.origin );
    }

    if ( isdefined( self._id_32AF ) )
        self._id_32AF scripts\engine\utility::_id_46C3( 0.05, ::_id_B607 );

    self._id_1042E[0] setscriptablepartstate( "uplink_drone_hide", "show", 0 );
    thread _id_07AD::_id_C78A();
}

_id_2113( var_0 )
{
    var_0._id_32C6 _id_2127( 0, 1 );
}

_id_20F5( var_0 )
{
    self endon( "pickup_object" );
    _id_07AD::_id_1574( "none" );
    self._id_89E5 = 1;
    wait( var_0 );
    self._id_89E5 = 0;
    _id_2165();
    _id_07AD::_id_1574( "any" );
    self notify( "ball_ready" );

    if ( !istrue( level._id_48BE ) )
    {
        playfx( level._effect["ball_download_end"], self._id_411F );
        thread _id_20F9( 0, 1 );
    }

    if ( scripts\mp\utility\game::getgametype() == "tdef" )
    {
        level _id_FD64( "neutral", 1, 1 );
        level._id_218A[0] thread _id_E6B7();
    }
}

_id_10821( var_0 )
{
    self endon( "pickup_object" );
    self endon( "game_ended" );
    _id_07AD::_id_1574( "none" );

    if ( level._id_2169 != 0 )
        scripts\mp\hostmigration::waitlongdurationwithhostmigrationpause( level._id_2169 );

    if ( level._id_F260 )
        level scripts\mp\gamelogic::resumetimer();

    _id_07AD::_id_D678( var_0._id_22FB, ( 0, 0, 0 ) );
    self._id_1042E[0] setscriptablepartstate( "uplink_drone_hide", "show", 0 );
    thread _id_20F5( 0 );
    var_0 _meth_82A7( ( 0, 720, 0 ), 3, 0, 3 );
}

_id_E6B7()
{
    self endon( "death" );
    self endon( "reset" );
    self endon( "pickup_object" );
    self notify( "hoverAnimStart" );
    self endon( "hoverAnimStart" );
    var_0 = self._id_1042E[0].origin;
    self._id_1042E[0] rotateyaw( 2000, 60, 0.2, 0.2 );

    for (;;)
    {
        self._id_1042E[0] moveto( var_0 + ( 0, 0, 5 ), 1, 0.5, 0.5 );
        wait 1;
        self._id_1042E[0] moveto( var_0 - ( 0, 0, 5 ), 1, 0.5, 0.5 );
        wait 1;
    }
}

_id_211E()
{
    self endon( "reset" );
    self endon( "pickup_object" );
    var_0 = self._id_1042E[0];
    var_1[0] = 200;
    var_1[1] = 200;
    var_1[2] = 1000;
    var_2[0] = 200;
    var_2[1] = 200;
    var_2[2] = 200;

    for (;;)
    {
        for ( var_3 = 0; var_3 < 2; var_3++ )
        {
            if ( var_0.origin[var_3] > level._id_210B[var_3] + var_1[var_3] )
            {
                _id_2127( 1, 1 );
                return;
            }

            if ( var_0.origin[var_3] < level._id_210C[var_3] - var_2[var_3] )
            {
                _id_2127( 1, 1 );
                return;
            }
        }

        waitframe();
    }
}

_id_211F( var_0 )
{
    self endon( "reset" );
    self endon( "pickup_object" );
    self endon( "score_event" );

    if ( !isdefined( level._id_7CB5 ) )
        level._id_7CB5 = 15;

    var_1 = level._id_7CB5;
    var_2 = 10;
    var_3 = 3;

    if ( var_1 >= var_2 )
    {
        wait( var_3 );
        var_1 = var_1 - var_3;
    }

    wait( var_1 );
    self notify( "physics_timeout" );
    _id_2127( 1, 1 );
}

_id_211A()
{
    self._id_1042E[0] endon( "physics_finished" );
    self endon( "physics_timeout" );
    self endon( "pickup_object" );
    self endon( "reset" );
    self endon( "score_event" );
    thread _id_2119();

    for (;;)
    {
        if ( self._id_1042E[0] _id_F390() )
            thread _id_211B( 1 );

        if ( !self._id_1042E[0] _id_0A67::_id_F38D() )
        {
            if ( self._id_1042E[0] _id_0A67::_id_F38C() || self._id_1042E[0] _id_0A67::_id_F391() )
            {
                _id_2127( 0, 1 );
                return;
            }
        }

        waitframe();
    }
}

_id_F390()
{
    if ( level._id_A6BA.size > 0 )
    {
        foreach ( var_1 in level._id_A6BA )
        {
            if ( self _meth_81EF( var_1 ) )
                return 1;
        }
    }

    return 0;
}

_id_10C06()
{
    self._id_1042E[0] endon( "physics_finished" );
    self endon( "physics_timeout" );
    self endon( "pickup_object" );
    self endon( "reset" );
    self endon( "score_event" );
    var_0 = gettime();
    var_1 = var_0 + 500;

    for (;;)
    {
        if ( self._id_1042E[0] _id_F390() && var_1 < var_0 )
        {
            _id_2127( 1, 1 );
            return;
        }

        wait 0.05;
        var_0 = gettime();
    }
}

_id_2119()
{
    self endon( "pickup_object" );
    self endon( "reset" );
    self endon( "score_event" );
    var_0 = self._id_1042E[0];
    var_0 endon( "death" );
    var_0 waittill( "physics_finished" );

    if ( _id_0A67::_id_F38C() )
    {
        _id_2127( 1, 1 );
        return;
    }
}

_id_210A()
{
    for (;;)
    {
        var_0 = scripts\engine\utility::_id_10897( "pickup_object", "dropped", "reset", "ball_ready" );

        switch ( var_0 )
        {
            case "pickup_object":
                break;
            case "dropped":
                break;
            case "reset":
                break;
            case "ball_ready":
                break;
            default:
                break;
        }
    }
}

_id_20EC( var_0 )
{
    self endon( "death_or_disconnect" );
    var_0 endon( "reset" );
    var_1 = spawnstruct();
    var_1 endon( "timer_done" );
    var_1 thread _id_F24D( 1.5 );
    var_0 waittill( "pickup_object" );
    var_1 _id_F246();

    if ( !isdefined( var_0._id_32AF ) || var_0._id_32AF.team == self.team )
        return;

    var_0._id_32AF endon( "disconnect" );
    var_1 thread _id_F24D( 5 );
    var_0._id_32AF waittill( "death", var_2 );
    var_1 _id_F246();

    if ( !isdefined( var_2 ) || var_2 != self )
        return;

    var_1 thread _id_F24D( 2 );
    var_0 waittill( "pickup_object" );
    var_1 _id_F246();

    if ( isdefined( var_0._id_32AF ) && var_0._id_32AF == self )
        thread _id_0A76::_id_6FE6( "ball_pass_kill" );
}

_id_F24D( var_0 )
{
    self endon( "cancel_timer" );
    wait( var_0 );
    self notify( "timer_done" );
}

_id_F246()
{
    self notify( "cancel_timer" );
}

_id_2165()
{
    _id_07AD::_id_D60F( "waypoint_neutral_ball", "waypoint_neutral_ball" );
}

_id_2164( var_0 )
{
    if ( scripts\mp\utility\game::getgametype() == "ball" )
        var_1 = "waypoint_escort";
    else
        var_1 = "waypoint_defend_round";

    _id_07AD::_id_D60F( var_1, "waypoint_capture_kill_round" );
}

_id_2163()
{
    if ( scripts\mp\utility\game::getgametype() == "ball" )
        var_0 = "waypoint_ball_download";
    else
        var_0 = "waypoint_reset_marker";

    _id_07AD::_id_D60F( var_0, var_0 );
}

_id_2167()
{
    _id_07AD::_id_D60F( "waypoint_ball_upload", "waypoint_ball_upload" );
}

_id_2126()
{
    self._id_1042E[0] solid();
}

_id_20F3()
{
    self._id_1042E[0] dontinterpolate();
    self._id_20F8 = 0;
}

_id_20E4( var_0 )
{
    foreach ( var_2 in self._id_1042E )
        var_2._id_22FB = var_0.origin;

    self._id_047A._id_22FB = var_0.origin;
    self._id_417C = var_0;
    var_0._id_7D63 = 1;
}

_id_20F0()
{
    if ( isdefined( self.killcament ) )
        self.killcament delete();

    self.killcament = spawn( "script_model", self._id_1042E[0].origin );
    self.killcament linkto( self._id_1042E[0] );
    self.killcament notsolid();
    self.killcament _meth_8374( "explosive" );
}

_id_812A()
{
    level._id_218B = level._id_BA03;
    level._id_218C = 1;
    level._id_218D = 0;

    if ( isdefined( level._id_BA02 ) && level._id_BA02 != 0 )
        thread _id_3FD3();
    else
    {

    }
}

_id_3FD3()
{
    level endon( "game_ended" );
    _id_07A8::_id_60A3( "prematch_done" );
    _id_FD64( "neutral", 1, 1 );
}

_id_FD64( var_0, var_1, var_2, var_3 )
{
    if ( !istrue( level._id_BA02 ) )
        return;

    var_4 = undefined;
    var_5 = 1000 * level._id_BA03;

    if ( istrue( var_2 ) )
    {
        if ( istrue( level._id_2169 ) && !istrue( level._id_2188 ) )
            var_5 = 1000 * level._id_2169;
    }

    if ( istrue( var_2 ) || istrue( var_3 ) )
    {
        level._id_218B = level._id_BA03;
        level._id_216E = int( gettime() + var_5 );
    }
    else
        level._id_216E = int( gettime() + 1000 * level._id_218B );

    setomnvar( "ui_hardpoint_timer", level._id_216E );

    if ( var_5 > 0 && ( istrue( var_3 ) || !var_1 && level._id_218C ) )
        level._id_20E2 thread _id_2189( var_0, var_4 );

    if ( var_1 )
        level _id_AF54();
}

_id_2189( var_0, var_1 )
{
    level endon( "game_ended" );
    level endon( "reset" );
    level endon( "pause_ball_timer" );
    level notify( "ballRunTimer" );
    level endon( "ballRunTimer" );
    level._id_218C = 0;
    _id_218E( var_0, var_1 );

    if ( !istrue( level._id_2188 ) )
    {
        _id_07AD::_id_1574( "none" );
        _id_212A( 1, self._id_047A.origin, 1 );
        _id_2127( 1, 1 );
    }
}

_id_218E( var_0, var_1 )
{
    level endon( "game_ended" );
    level endon( "pause_ball_timer" );
    var_2 = scripts\engine\utility::ter_op( isdefined( var_1 ), var_1, int( level._id_218B * 1000 + gettime() ) );
    level _id_C720( var_1 );
    thread _id_10C17();
    level thread _id_743C( var_2 );
    _id_107E0( level._id_218B );
}

_id_107E0( var_0 )
{
    level endon( "game_ended" );
    level endon( "pause_ball_timer" );

    if ( var_0 == 0 )
        return;

    var_1 = gettime();
    var_2 = gettime() + var_0 * 1000;

    while ( gettime() < var_2 )
    {
        _id_10947( ( var_2 - gettime() ) / 1000 );

        while ( isdefined( level._id_7A93 ) )
        {
            var_2 = var_2 + 1000;
            setclientnamemode( int( var_2 ) );
            wait 1;
        }
    }

    while ( isdefined( level._id_7A93 ) )
    {
        var_2 = var_2 + 1000;
        setclientnamemode( int( var_2 ) );
        wait 1;
    }

    return gettime() - var_1;
}

_id_10947( var_0 )
{
    level endon( "game_ended" );
    level endon( "pause_ball_timer" );

    if ( isdefined( level._id_7A93 ) )
        return;

    level endon( "host_migration_begin" );
    wait( var_0 );
}

_id_743C( var_0 )
{
    level endon( "game_ended" );
    level endon( "disconnect" );
    level waittill( "host_migration_begin" );
    setomnvar( "ui_objective_timer_stopped", 1 );
    var_1 = scripts\mp\hostmigration::_id_10956();

    if ( !level._id_218D )
        setomnvar( "ui_objective_timer_stopped", 0 );

    if ( var_1 > 0 )
        setomnvar( "ui_hardpoint_timer", level._id_216E + var_1 );
    else
        setomnvar( "ui_hardpoint_timer", level._id_216E );
}

_id_10C17()
{
    level endon( "game_ended" );
    level notify( "watchResetSoon" );
    level endon( "watchResetSoon" );
    var_0 = 0;

    for ( var_1 = undefined; level._id_218B > 0 && !level._id_218C; level._id_218B = level._id_218B - var_6 )
    {
        var_2 = gettime();

        if ( !var_0 && level._id_218B < 10 )
        {
            foreach ( var_4 in level._id_EF86 )
                level _id_0A64::_id_E772( "drone_reset_soon", var_4 );

            var_0 = 1;
        }

        if ( isdefined( level._id_218A[0]._id_32AF ) && level._id_218B < 5 )
        {
            if ( !isdefined( var_1 ) || var_2 > var_1 + 1000 )
                var_1 = var_2;
        }

        var_6 = 0.05;
        wait( var_6 );
    }

    if ( level._id_218C )
        level notify( "pause_ball_timer" );
}

_id_FC0D( var_0 )
{
    var_1 = level._id_218C || isdefined( level._id_7A93 );

    if ( !_id_07A8::_id_609F( "prematch_done" ) )
        var_1 = 0;

    if ( !level._id_218D && var_1 )
    {
        level._id_218D = 1;
        setomnvar( "ui_objective_timer_stopped", 1 );
    }
    else if ( level._id_218D && !var_1 )
    {
        level._id_218D = 0;
        setomnvar( "ui_objective_timer_stopped", 0 );
    }
}

_id_AF54()
{
    level._id_218C = 1;
    _id_FC0D();
}

_id_C720( var_0 )
{
    level._id_218C = 0;
    _id_FC0D( var_0 );
}

_id_2125()
{
    if ( !istrue( level._id_48BE ) )
    {
        foreach ( var_1 in level._id_218A )
            var_1 _id_20FA( self );
    }
}

_id_20FA( var_0 )
{
    if ( _id_20F8() )
    {
        self._id_1042E[0] setscriptablepartstate( "uplink_drone_idle", "normal", 0 );
        self._id_1042E[0] setscriptablepartstate( "uplink_drone_tail", "normal", 0 );
    }
}

_id_20F9( var_0, var_1 )
{
    self endon( "reset" );
    self endon( "pickup_object" );

    if ( istrue( var_0 ) )
        wait 0.2;
    else
        waitframe();

    if ( !_id_20F8() )
    {
        self._id_1042E[0] setscriptablepartstate( "uplink_drone_idle", "normal", 0 );
        self._id_1042E[0] setscriptablepartstate( "uplink_drone_tail", "normal", 0 );
        self._id_20F8 = 1;
    }
}

_id_20F8()
{
    return isdefined( self._id_20F8 ) && self._id_20F8;
}

_id_20FB()
{
    if ( _id_20F8() )
        self._id_1042E[0] _id_E89A();

    self._id_20F8 = 0;
}

_id_E89A()
{
    self setscriptablepartstate( "uplink_drone_idle", "off", 0 );
    self setscriptablepartstate( "uplink_drone_tail", "off", 0 );
}

_id_20F4( var_0, var_1 )
{
    scripts\engine\utility::_id_108F3( "pickup_object", var_1 );
    level._id_CBF8 = 0;
    level notify( "goal_ready" );
}

_id_A211()
{
    level notify( "practice" );
    level endon( "practice" );
    level endon( "game_ended" );
    wait 5;

    for (;;)
    {
        self waittill( "call_ball" );

        if ( !isdefined( level._id_218A[0]._id_32AF ) )
        {
            level._id_218A[0]._id_1042E[0] physicslaunchserver( level._id_218A[0]._id_1042E[0].origin, ( 0, 0, 0 ) );
            level._id_218A[0]._id_1042E[0] _meth_8544();

            while ( !isdefined( level._id_218A[0]._id_32AF ) )
            {
                var_0 = 40;

                switch ( self getstance() )
                {
                    case "crouch":
                        var_0 = 30;
                        break;
                    case "prone":
                        var_0 = 15;
                        break;
                }

                level._id_218A[0]._id_1042E[0] moveto( self.origin + ( 0, 0, var_0 ), 0.3, 0.15, 0.1 );
                wait 0.1;
            }
        }

        wait 1;
    }
}

_id_BB1F()
{
    level endon( "game_ended" );
    self endon( "disconnect" );
    var_0 = 1;

    for (;;)
    {
        if ( var_0 )
            self waittill( "giveLoadout" );
        else
            self waittill( "spawned" );

        var_0 = 0;

        if ( var_0 )
            wait 20;
        else
            wait 2;

        thread _id_6FB7();
    }
}

_id_6FB7()
{
    self notify( "practiceMessage" );
    self endon( "practiceMessage" );
    self endon( "death_or_disconnect" );
    level endon( "game_ended" );

    if ( scripts\engine\utility::is_player_gamepad_enabled() )
    {
        self notifyonplayercommand( "call_ball", "+actionslot 3" );
        self iprintlnbold( &"PLATFORM/UPLINK_PRACTICE_SLOT3" );
    }
    else
    {
        self notifyonplayercommand( "call_ball", "+actionslot 7" );
        self iprintlnbold( &"PLATFORM/UPLINK_PRACTICE_SLOT7" );
    }

    level._id_218A[0] waittill( "score_event" );
    wait 5;
    thread _id_6FB7();
}

_id_E028( var_0 )
{
    if ( !isdefined( var_0 ) || var_0.size == 0 )
        return undefined;

    var_1 = 1;

    for ( var_2 = var_0.size; var_1; var_2-- )
    {
        var_1 = 0;

        for ( var_3 = 0; var_3 < var_2 - 1; var_3++ )
        {
            if ( _id_3AD4( var_0[var_3], var_0[var_3 + 1] ) )
            {
                var_4 = var_0[var_3];
                var_0[var_3] = var_0[var_3 + 1];
                var_0[var_3 + 1] = var_4;
                var_1 = 1;
            }
        }
    }

    return var_0;
}

_id_3AD4( var_0, var_1 )
{
    var_2 = int( var_0._id_CD8C );
    var_3 = int( var_1._id_CD8C );

    if ( !isdefined( var_2 ) && !isdefined( var_3 ) )
        return 0;

    if ( !isdefined( var_2 ) && isdefined( var_3 ) )
        return 1;

    if ( isdefined( var_2 ) && !isdefined( var_3 ) )
        return 0;

    if ( var_2 > var_3 )
        return 1;

    return 0;
}

_id_6BF3()
{
    var_0 = 0;

    switch ( self getstance() )
    {
        case "crouch":
            var_0 = 5;
            break;
        case "prone":
            var_0 = 10;
            break;
    }

    var_1 = self _meth_8540();
    var_2 = anglestoup( var_1 );
    var_3 = self geteye() + var_2 * var_0;
    return var_3;
}

_id_6BF2()
{
    var_0 = self getplayerangles();
    var_1 = anglestoforward( var_0 );
    return var_1;
}

_id_6DA4()
{
    var_0 = 10;

    switch ( self getstance() )
    {
        case "crouch":
            var_0 = 15;
            break;
        case "prone":
            var_0 = 5;
            break;
    }

    var_1 = self _meth_8540();
    var_2 = anglestoup( var_1 );
    var_3 = self gettagorigin( "j_spinelower", 1, 1 );
    var_4 = var_3 + var_2 * var_0;
    return var_4;
}

_id_6DA3()
{
    var_0 = _id_6DA4();
    return ( 0, 0, var_0[2] - self.origin[2] );
}
