// S4 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

main()
{
    if ( isdefined( self._id_03E1 ) )
        return;

    self endon( "death" );
    self endon( "stealth_disabled" );
    self._id_03E1 = spawnstruct();
    _id_088C::_id_71EF( "stealth_spotted" );
    scripts\engine\utility::_id_5453( "stealth_enabled" );
    scripts\engine\utility::_id_5454( "stealth_enabled" );
    scripts\engine\utility::_id_5453( "stealth_in_shadow" );
    scripts\engine\utility::_id_5453( "stealth_use_real_lighting" );
    scripts\engine\utility::_id_5454( "stealth_use_real_lighting" );
    self._id_03E1._id_E436 = [];
    _id_088C::_id_71DA();
    thread _id_9CA5();

    if ( scripts\common\utility::_id_8A2C() )
        thread _id_E7F9();
}

_id_9CA5()
{
    self endon( "death" );
    self endon( "disconnect" );

    for (;;)
    {
        if ( _id_9CA4() )
            self._id_0283 = _id_642A();

        waitframe();
    }
}

_id_9CA4()
{
    if ( istrue( self._id_9CA6 ) )
        return 0;

    if ( !scripts\engine\utility::_id_544E( "stealth_enabled" ) )
        return 0;

    if ( scripts\engine\utility::_id_544E( "stealth_in_shadow" ) )
        return 1;

    if ( isdefined( self._id_947D ) && gettime() < self._id_947D )
        return 0;

    return 1;
}

_id_642A()
{
    var_0 = self getstance();

    if ( _id_088C::_id_71FF() )
        var_1 = "spotted";
    else
        var_1 = "hidden";

    var_2 = level._id_03E1._id_4871._id_C00D[var_1][var_0];
    var_3 = 0;

    if ( scripts\engine\utility::_id_544E( "stealth_in_shadow" ) )
    {
        var_2 = var_2 * level._id_03E1._id_4871._id_C00D[var_1]["shadow"];
        var_3 = 1;
    }
    else if ( scripts\engine\utility::_id_544E( "stealth_use_real_lighting" ) )
    {
        var_2 = var_2 * self _meth_8624();
        var_3 = 1;
    }

    if ( var_3 )
        var_2 = max( var_2, level._id_03E1._id_4871._id_9F20[var_1][var_0] );

    return var_2;
}

_id_3AA5( var_0 )
{
    if ( !isdefined( var_0 ) )
        var_0 = 1;

    if ( !var_0 )
    {
        self notify( "stop_player_combat_state_thread" );
        self._id_03E1._id_3AA2 = undefined;
        return;
    }
    else if ( isdefined( self._id_03E1._id_3AA2 ) )
        return;

    self endon( "death" );
    self endon( "stealth_disabled" );
    self endon( "stop_player_combat_state_thread" );
    self endon( "disconnect" );
    childthread _id_B64D();
    childthread _id_3AA6();
    self._id_03E1._id_3AA2 = spawnstruct();
    self._id_03E1._id_3AA2.name = "stealth";
    self._id_03E1._id_3AA2._id_048F = "idle";
    self._id_03E1._id_3AA2._id_FC71 = [];
    var_1 = [];
    var_2 = [];

    for (;;)
    {
        scripts\engine\utility::_id_5456( "stealth_enabled" );
        var_1 = scripts\engine\utility::_id_1BA9( var_1 );
        var_1 = scripts\engine\utility::_id_1BA2( var_1 );
        var_2 = scripts\engine\utility::_id_1BA9( var_2 );
        var_2 = scripts\engine\utility::_id_1BA2( var_2 );
        var_3 = [];
        var_4 = [];
        var_5 = 0;

        if ( isdefined( self._id_8F79 ) && !scripts\engine\utility::_id_F1E8( self._id_8F79, 10 ) )
            var_5 = 1;

        foreach ( var_7 in _func_0070( "axis" ) )
        {
            if ( !isalive( var_7 ) )
                continue;

            if ( !scripts\engine\utility::array_contains( var_1, var_7 ) )
            {
                if ( var_7._id_0168 )
                    continue;

                if ( scripts\engine\utility::is_equal( var_7._id_036A, "pain" ) )
                    continue;
            }

            if ( var_7 [[ var_7._id_5D78 ]]() )
            {
                if ( isdefined( self._id_03E1._id_3AA2._id_9C47 ) )
                {
                    var_8 = self._id_03E1._id_3AA2._id_9C47;

                    if ( distancesquared( self.origin, var_7.origin ) > _func_0214( var_8 ) )
                    {
                        var_4[var_4.size] = var_7;
                        continue;
                    }
                }

                var_3[var_3.size] = var_7;

                if ( var_5 )
                    continue;

                if ( !scripts\engine\utility::is_equal( var_7._id_017D, self ) )
                    continue;

                if ( var_7 _meth_8066( self ) )
                    var_5 = 1;

                continue;
            }

            if ( var_7 [[ var_7._id_5D79 ]]() )
                var_4[var_4.size] = var_7;
        }

        var_10 = self._id_03E1._id_3AA2.name;
        var_11 = self._id_03E1._id_3AA2._id_048F;
        var_12 = var_10;
        var_13 = undefined;

        if ( var_10 == "combat" )
        {
            if ( var_3.size == 0 )
            {
                var_12 = "stealth";

                if ( scripts\engine\utility::_id_1B8C( var_1, var_4 ).size > 0 )
                    var_13 = "hunt";
                else if ( var_4.size == 0 )
                    var_13 = "all_clear";
                else
                    var_13 = "combat_clear";
            }
            else if ( scripts\engine\utility::is_equal( var_11, "unaware" ) && var_5 )
                var_13 = "aware";
        }
        else if ( var_3.size > 0 )
        {
            var_12 = "combat";

            if ( var_5 )
                var_13 = "aware";
            else
                var_13 = "unaware";
        }
        else if ( scripts\engine\utility::is_equal( var_11, "hunt" ) && var_4.size == 0 )
            var_13 = "all_clear";

        if ( var_12 != var_10 || isdefined( var_13 ) && !scripts\engine\utility::is_equal( var_13, var_11 ) )
        {
            self._id_03E1._id_3AA2.name = var_12;
            self._id_03E1._id_3AA2._id_048F = var_13;
            self notify( "player_combat_state_updated", var_12, var_13 );
        }

        var_1 = var_3;
        var_2 = var_4;
        waitframe();
    }
}

_id_3AA6()
{
    for (;;)
    {
        self waittill( "player_combat_state_updated", var_0, var_1 );

        foreach ( var_3 in self._id_03E1._id_3AA2._id_FC71 )
            self thread [[ var_3 ]]( var_0, var_1 );
    }
}

_id_3AA3( var_0, var_1 )
{
    self._id_03E1._id_3AA2._id_FC71[var_0] = var_1;
}

_id_3AA4( var_0 )
{
    self._id_03E1._id_3AA2._id_FC71 = scripts\engine\utility::_id_1B9E( self._id_03E1._id_3AA2._id_FC71, var_0 );
}

_id_B64D()
{
    for (;;)
    {
        level scripts\engine\utility::waittill_any_2( "an_enemy_shot", "enemy_grenade_fire" );
        self._id_8F79 = gettime();
    }
}

_id_E7F9()
{
    self endon( "stealth_disabled" );
    self._id_03E1._id_797D = spawnstruct();
    self._id_03E1._id_797D._id_3325 = undefined;
    self._id_03E1._id_797D._id_8510 = [];
    self._id_03E1._id_797D._id_43CD["footstep_sprint"] = 6;
    self._id_03E1._id_797D._id_43CD["gunshot"] = 8;
    self._id_03E1._id_797D._id_43CD["proximity_speed"] = 16;
    self._id_03E1._id_797D._id_43CD["sight_standing"] = 19;
    childthread _id_E7F8();
    childthread _id_E7F7();
    childthread _id_E7F6();
}

_id_E7F8()
{
    self endon( "death" );

    for (;;)
    {
        scripts\engine\utility::_id_5456( "stealth_enabled" );
        level waittill( "stealth_event", var_0, var_1 );

        if ( !isalive( var_1 ) )
            continue;

        if ( !scripts\engine\utility::is_equal( var_0._id_0186, level.player ) )
            continue;

        if ( !scripts\engine\utility::_id_544E( "stealth_enabled" ) )
        {
            self._id_03E1._id_797D._id_3325 = undefined;
            self._id_03E1._id_797D._id_8510 = [];
            continue;
        }

        if ( _id_088C::_id_18DF() )
        {
            if ( var_0._id_048F != "combat" )
                continue;

            var_2 = 0;

            foreach ( var_4 in _func_0070( var_1.team ) )
            {
                if ( var_4 == var_1 )
                    continue;

                if ( var_4 [[ var_4._id_5D78 ]]() )
                {
                    var_2 = 1;
                    break;
                }
            }

            if ( var_2 )
                continue;
        }

        var_6 = var_0._id_F8E1;

        if ( var_6 == "gunshot" && !istrue( level._id_759E ) )
            continue;

        if ( ( var_6 == "sight" || var_6 == "proximity" ) && self issprinting() )
            var_6 = "footstep_sprint";
        else if ( var_6 == "proximity" && _func_0132( level.player getvelocity() ) > 11025 )
            var_6 = "proximity_speed";
        else if ( var_6 == "sight" && self getstance() == "stand" )
            var_6 = "sight_standing";

        if ( !isdefined( self._id_03E1._id_797D._id_43CD[var_6] ) )
            continue;

        if ( scripts\engine\utility::array_contains( self._id_03E1._id_797D._id_8510, var_1 ) )
            continue;

        childthread _id_E7F5( var_1, var_6 );
    }
}

_id_E7F5( var_0, var_1 )
{
    self endon( "combat_started" );
    self endon( "stealth_enabled" );
    self._id_03E1._id_797D._id_8510[self._id_03E1._id_797D._id_8510.size] = var_0;

    if ( var_0 [[ var_0._id_5D79 ]]() )
    {
        var_0 scripts\engine\utility::_id_46C3( 10, scripts\engine\utility::_id_D0A1, "stealthHints_timeout" );
        var_0 scripts\engine\utility::_id_1087F( "stealth_combat", "death", "stealthHints_timeout" );
    }
    else if ( var_0 [[ var_0._id_5D7C ]]() )
        var_0 scripts\engine\utility::_id_1087F( "stealth_idle", "stealth_combat", "death" );

    self._id_03E1._id_797D._id_8510 = scripts\engine\utility::array_remove( self._id_03E1._id_797D._id_8510, var_0 );

    if ( !isalive( var_0 ) || !var_0 [[ var_0._id_5D78 ]]() )
        return;

    self._id_03E1._id_797D._id_3325 = var_1;
    self._id_03E1._id_797D._id_8510 = [];
    self notify( "combat_started" );
}

_id_E7F7()
{
    self waittill( "death" );

    if ( !scripts\engine\utility::_id_544E( "stealth_enabled" ) )
        return;

    if ( isdefined( level._id_4214 ) )
        return;

    if ( !isdefined( self._id_03E1._id_797D._id_3325 ) )
        return;

    level._id_4214 = self._id_03E1._id_797D._id_43CD[self._id_03E1._id_797D._id_3325];
}

_id_E7F6()
{
    self endon( "death" );

    for (;;)
    {
        scripts\engine\utility::_id_5456( "stealth_enabled" );

        while ( !isdefined( self._id_03E1._id_797D._id_3325 ) )
            waitframe();

        while ( _id_088C::_id_18DF() )
            waitframe();

        self._id_03E1._id_797D._id_3325 = undefined;
    }
}
