// S4 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

_id_273D()
{
    var_0 = _id_273C( self._id_410C );

    if ( isdefined( var_0 ) && var_0.size > 0 )
        return scripts\engine\utility::random( var_0 ).origin;

    return undefined;
}

_id_273C( var_0, var_1 )
{
    if ( isdefined( self._id_45BA ) )
        return _id_09D1::_id_2797( var_0, self._id_45BA, var_1 );

    return [];
}

_id_2790( var_0, var_1, var_2 )
{
    if ( self _meth_802F( "allowGrenades" ) == 0 )
        return undefined;

    var_3 = [];
    var_3[var_3.size] = var_0;

    if ( isdefined( var_1 ) )
        var_3[var_3.size] = var_1;

    if ( isdefined( var_1 ) )
        var_3[var_3.size] = var_2;

    if ( var_3.size == 0 )
        return undefined;

    var_4 = self getweaponslistall();
    var_5 = [];

    foreach ( var_7 in var_4 )
    {
        if ( self getweaponammoclip( var_7 ) > 0 || self getweaponammostock( var_7 ) > 0 )
            var_5[var_5.size] = var_7;
    }

    if ( var_5.size <= 0 )
        return undefined;

    foreach ( var_10 in var_3 )
    {
        foreach ( var_7 in var_5 )
        {
            if ( _id_09D1::_id_27EC( var_10, var_7 ) )
            {
                var_12["purpose"] = var_10;
                var_13 = self _meth_802C( "lethal" );

                if ( isdefined( var_13 ) && var_7 == var_13 )
                    var_12["item_action"] = "lethal";

                var_14 = self _meth_802C( "tactical" );

                if ( isdefined( var_14 ) && var_7 == var_14 )
                    var_12["item_action"] = "tactical";

                var_12["weap_name"] = var_7;
                return var_12;
            }
        }
    }
}

_id_289B( var_0, var_1, var_2, var_3, var_4 )
{
    self notify( "bot_set_ambush_trap" );
    self endon( "bot_set_ambush_trap" );

    if ( !isdefined( var_0 ) )
        return 0;

    var_5 = undefined;

    if ( !isdefined( var_4 ) && isdefined( var_1 ) && var_1.size > 0 )
    {
        if ( !isdefined( var_2 ) )
            return 0;

        var_6 = [];
        var_7 = undefined;

        if ( isdefined( var_3 ) )
            var_7 = anglestoforward( ( 0, var_3, 0 ) );

        foreach ( var_9 in var_1 )
        {
            if ( !isdefined( var_7 ) )
            {
                var_6[var_6.size] = var_9;
                continue;
            }

            if ( distancesquared( var_9.origin, var_2.origin ) > 90000 )
            {
                if ( vectordot( var_7, vectornormalize( var_9.origin - var_2.origin ) ) < 0.4 )
                    var_6[var_6.size] = var_9;
            }
        }

        if ( var_6.size > 0 )
        {
            var_5 = scripts\engine\utility::random( var_6 );
            var_11 = _func_00B4( var_5.origin, 300, 50 );
            var_12 = [];

            foreach ( var_14 in var_11 )
            {
                if ( !isdefined( var_14._id_26D8 ) )
                    var_12[var_12.size] = var_14;
            }

            var_11 = var_12;
            var_4 = self _meth_8048( var_11, min( var_11.size, 3 ), "node_trap", var_2, var_5 );
        }
    }

    if ( isdefined( var_4 ) )
    {
        var_16 = undefined;

        if ( var_0["purpose"] == "trap_directional" && isdefined( var_5 ) )
        {
            var_17 = vectortoangles( var_5.origin - var_4.origin );
            var_16 = var_17[1];
        }

        if ( self _meth_8041() && self _meth_803D() != "critical" && self _meth_803D() != "tactical" )
            self _meth_802A();

        var_18 = self _meth_8058( var_4, "guard", var_16 );

        if ( var_18 )
        {
            var_19 = _id_09D1::_id_28F6();

            if ( var_19 == "goal" )
            {
                thread _id_09D1::_id_2775( "stand", 4.0 );

                if ( !isdefined( self._id_017D ) || !self _meth_8027( self._id_017D ) )
                {
                    thread _id_09D1::_id_274E( 4.0 );
                    var_20 = ( 0, 0, 0 );

                    if ( issubstr( var_0["weap_name"].basename, "claymore" ) )
                        var_20 = ( 0, 0, 55 );

                    if ( isdefined( var_16 ) )
                        self _meth_8044( var_5.origin + var_20, 3.0, "script_forced" );
                    else
                        self _meth_8044( self.origin + var_20 + anglestoforward( self getplayerangles() ) * 50, 3.0, "script_forced" );

                    if ( !isdefined( var_0["item_action"] ) )
                        var_0 = _id_2790( "trap_directional", "trap" );

                    if ( isdefined( var_0["item_action"] ) )
                        _id_28E5( var_0["item_action"] );

                    self._id_1695 = undefined;
                    thread _id_289C( "grenade_fire" );
                    thread _id_289C( "missile_fire" );
                    var_21 = scripts\engine\utility::ter_op( isdefined( var_0["purpose"] ) && var_0["purpose"] == "tacticalinsertion", 6.0, 3.0 );
                    scripts\engine\utility::_id_108A6( var_21, "missile_fire", "grenade_fire" );
                    wait 0.05;
                    self notify( "ambush_trap_ent" );

                    if ( isdefined( self._id_1695 ) && isdefined( var_0["purpose"] ) && var_0["purpose"] == "c4" )
                        thread _id_28FD( self._id_1695, 300 );

                    self._id_1695 = undefined;
                    wait( randomfloat( 0.25 ) );
                    self notify( "bot_force_stance_for_time" );
                    self _meth_805A( "none" );
                    self _meth_83FF( "none" );
                    self notify( "bot_disable_movement_for_time" );
                    self _meth_8053( "disable_movement", 0 );
                    self _meth_8044( undefined );
                }
            }

            return 1;
        }
    }

    return 0;
}

_id_28E5( var_0 )
{
    self endon( "grenade_pullback" );

    for (;;)
    {
        self _meth_804D( var_0 );
        wait 0.5;
    }
}

_id_289C( var_0 )
{
    self endon( "death_or_disconnect" );
    self endon( "bot_set_ambush_trap" );
    self endon( "ambush_trap_ent" );
    level endon( "game_ended" );
    self waittill( var_0, var_1 );
    self._id_1695 = var_1;
}

_id_28FD( var_0, var_1 )
{
    self endon( "death_or_disconnect" );
    var_0 endon( "death" );
    level endon( "game_ended" );
    var_2 = var_1 * var_1;

    for (;;)
    {
        if ( distancesquared( self.origin, var_0.origin ) > var_2 )
        {
            var_3 = self _meth_8120( var_0.origin, 1.0 );

            if ( var_3 < var_2 )
            {
                self _meth_804D( "use", 0.25 );
                wait 0.5;
                self _meth_804D( "use", 0.25 );
                return;
            }
        }

        wait( randomfloatrange( 0.25, 1.0 ) );
    }
}

_id_2703( var_0, var_1, var_2 )
{
    thread _id_2741( var_0, var_1, "capture", var_2 );
}

_id_2704( var_0, var_1, var_2, var_3 )
{
    var_3["capture_trigger"] = var_2;
    thread _id_2741( var_0, var_1, "capture_zone", var_3 );
}

_id_2873( var_0, var_1, var_2 )
{
    if ( !isdefined( var_2 ) || !isdefined( var_2["min_goal_time"] ) )
        var_2["min_goal_time"] = 12;

    if ( !isdefined( var_2 ) || !isdefined( var_2["max_goal_time"] ) )
        var_2["max_goal_time"] = 18;

    thread _id_2741( var_0, var_1, "protect", var_2 );
}

_id_2874( var_0, var_1, var_2, var_3 )
{
    if ( !isdefined( var_3 ) || !isdefined( var_3["min_goal_time"] ) )
        var_3["min_goal_time"] = 12;

    if ( !isdefined( var_3 ) || !isdefined( var_3["max_goal_time"] ) )
        var_3["max_goal_time"] = 18;

    if ( !isdefined( var_3 ) || !isdefined( var_3["random_stance"] ) )
        var_3["random_stance"] = 1;

    var_3["uniqueID"] = var_2;
    thread _id_2741( var_1, var_0, "protect_zone", var_3 );
}

_id_2854( var_0, var_1, var_2 )
{
    if ( !isdefined( var_2 ) || !isdefined( var_2["min_goal_time"] ) )
        var_2["min_goal_time"] = 0.0;

    if ( !isdefined( var_2 ) || !isdefined( var_2["max_goal_time"] ) )
        var_2["max_goal_time"] = 0.01;

    thread _id_2741( var_0, var_1, "patrol", var_2 );
}

_id_27BD( var_0, var_1, var_2 )
{
    if ( !isdefined( var_2 ) || !isdefined( var_2["min_goal_time"] ) )
        var_2["min_goal_time"] = 15;

    if ( !isdefined( var_2 ) || !isdefined( var_2["max_goal_time"] ) )
        var_2["max_goal_time"] = 20;

    thread _id_2741( var_0, var_1, "bodyguard", var_2 );
}

_id_273F( var_0 )
{
    if ( var_0 == "protect_zone" )
        return 0;

    return 1;
}

_id_2741( var_0, var_1, var_2, var_3 )
{
    self notify( "started_bot_defend_think" );
    self endon( "started_bot_defend_think" );
    self endon( "death_or_disconnect" );
    level endon( "game_ended" );
    self endon( "defend_stop" );
    thread _id_4601();

    if ( isdefined( self._id_2743 ) || self _meth_803D() == "camp" )
        self _meth_802A();

    self._id_2743 = 1;
    self._id_2749 = var_2;

    if ( var_2 == "capture_zone" )
    {
        self._id_2747 = undefined;
        self._id_2745 = var_1;
        self._id_2748 = var_3["capture_trigger"];
    }
    else if ( var_2 == "protect_zone" )
    {
        self._id_2747 = undefined;
        self._id_2745 = var_1;
        self._id_274A = var_3["uniqueID"];
    }
    else
    {
        self._id_2747 = var_1;
        self._id_2745 = undefined;
        self._id_2748 = undefined;
    }

    if ( _id_0A67::_id_885D( var_0 ) )
    {
        self._id_273E = var_0;
        childthread _id_A0B3();
    }
    else
    {
        self._id_273E = undefined;
        self._id_2744 = var_0;
    }

    self _meth_805A( "none" );
    var_4 = undefined;
    var_5 = 6;
    var_6 = 10;
    self._id_4607 = [];

    if ( isdefined( var_3 ) )
    {
        self._id_45BA = var_3["entrance_points_index"];
        self._id_2746 = var_3["override_origin_node"];

        if ( isdefined( var_3["score_flags"] ) )
        {
            if ( _func_0106( var_3["score_flags"] ) )
                self._id_4607 = var_3["score_flags"];
            else
                self._id_4607[0] = var_3["score_flags"];
        }

        if ( isdefined( var_3["override_goal_type"] ) )
            var_4 = var_3["override_goal_type"];

        if ( isdefined( var_3["min_goal_time"] ) )
            var_5 = var_3["min_goal_time"];

        if ( isdefined( var_3["max_goal_time"] ) )
            var_6 = var_3["max_goal_time"];

        if ( isdefined( var_3["override_watch_nodes"] ) && var_3["override_watch_nodes"].size > 0 )
            self._id_4606 = var_3["override_watch_nodes"];

        self._id_45BF = var_3["objective_radius"];
    }

    if ( !isdefined( self._id_273E ) && _id_273F( var_2 ) )
    {
        var_7 = undefined;

        if ( isdefined( var_3 ) && isdefined( var_3["nearest_node_to_center"] ) )
            var_7 = var_3["nearest_node_to_center"];

        if ( !isdefined( var_7 ) && isdefined( self._id_2746 ) )
            var_7 = self._id_2746;

        if ( !isdefined( var_7 ) && isdefined( self._id_2748 ) && isdefined( self._id_2748._id_A3E5 ) )
            var_7 = self._id_2748._id_A3E5;

        if ( !isdefined( var_7 ) )
            var_7 = _func_0080( _id_09D1::_id_45C2() );

        if ( !isdefined( var_7 ) )
        {
            var_8 = _id_09D1::_id_45C2();
            var_9 = _func_00B5( var_8, 256, 0 );

            for ( var_10 = 0; var_10 < var_9.size; var_10++ )
            {
                var_11 = vectornormalize( var_9[var_10].origin - var_8 );
                var_12 = var_8 + var_11 * 15;

                if ( _func_01FD( var_12, var_9[var_10].origin, 0, undefined ) )
                {
                    var_7 = var_9[var_10];
                    break;
                }

                wait 0.05;

                if ( _func_01FD( var_12 + ( 0, 0, 55 ), var_9[var_10].origin + ( 0, 0, 55 ), 0, undefined ) )
                {
                    var_7 = var_9[var_10];
                    break;
                }

                wait 0.05;
            }
        }

        self._id_A53D = var_7;
    }
    else if ( isdefined( var_3 ) && isdefined( var_3["nearest_node_to_center"] ) )
        self._id_A53D = var_3["nearest_node_to_center"];

    var_13 = level._id_2769[var_2];

    if ( !isdefined( var_4 ) )
    {
        var_4 = "guard";

        if ( var_2 == "capture" || var_2 == "capture_zone" )
            var_4 = "objective";
    }

    var_14 = 0;
    var_15 = 0;

    if ( _id_09D1::_id_27DB() )
    {
        var_14 = 1;
        var_15 = isdefined( var_3 ) && isdefined( var_3["entrance_points_index"] ) && _func_0106( var_3["entrance_points_index"] );
    }
    else if ( isdefined( var_3 ) && istrue( var_3["random_stance"] ) )
    {
        var_14 = 1;
        var_15 = 1;
    }

    var_16 = 1;

    if ( isdefined( var_3 ) && istrue( var_3["dont_leave_goal_during_combat"] ) )
        var_16 = 0;

    if ( var_2 == "protect" )
        childthread _id_BDB2();

    for (;;)
    {
        self._id_BBF8 = self._id_410A;
        self._id_410A = undefined;
        self._id_4109 = undefined;
        self._id_410B = undefined;
        self._id_410C = _id_2EA9( var_14, var_15 );
        var_17 = self _meth_803D();
        var_18 = _id_09D1::_id_27B7( var_4, var_17 );

        if ( !var_18 )
        {
            wait 0.25;
            continue;
        }

        var_19 = var_5;
        var_20 = var_6;
        var_21 = 1;

        if ( isdefined( self._id_4604 ) )
        {
            self._id_410B = self._id_4604;
            self._id_4604 = undefined;
            var_21 = 0;
            var_19 = 1.0;
            var_20 = 2.0;
        }
        else if ( isdefined( self._id_4602 ) )
        {
            self._id_410A = self._id_4602;
            self._id_4602 = undefined;
        }
        else
        {
            if ( isdefined( level._id_11B5 ) && level._id_11B5[self.team] )
            {
                if ( !scripts\engine\utility::array_contains( self._id_4607, "avoid_aerial_enemies" ) )
                    self._id_4607[self._id_4607.size] = "avoid_aerial_enemies";
            }

            self [[ var_13 ]]();
        }

        self _meth_802A();
        var_22 = "";

        if ( isdefined( self._id_410A ) || isdefined( self._id_410B ) )
        {
            if ( var_21 && _id_09D1::_id_27E5() && !isplayer( var_0 ) && isdefined( self._id_45BA ) )
            {
                var_23 = _id_2790( "trap_directional", "trap", "c4" );

                if ( isdefined( var_23 ) )
                {
                    var_24 = _id_09D1::_id_2797( undefined, self._id_45BA );
                    _id_289B( var_23, var_24, self._id_A53D );
                }
            }

            if ( isdefined( self._id_410B ) )
            {
                var_25 = undefined;

                if ( isdefined( self._id_4109 ) )
                    var_25 = self._id_4109[1];

                self _meth_8057( self._id_410B, 0, var_4, var_25, self._id_45BF );
            }
            else if ( !isdefined( self._id_4109 ) )
                self _meth_8058( self._id_410A, var_4, undefined, self._id_45BF );
            else
                self _meth_8058( self._id_410A, var_4, self._id_4109[1], self._id_45BF );

            if ( var_14 )
            {
                if ( !isdefined( self._id_BBF8 ) || !isdefined( self._id_410A ) || self._id_BBF8 != self._id_410A )
                    self _meth_805A( "none" );
            }

            var_26 = self _meth_803A();
            self notify( "new_defend_goal" );
            _id_09D1::_id_10A77();

            if ( var_4 == "objective" )
            {
                _id_4600();
                self _meth_8050( 1.0 );
                self _meth_8053( "cautious", 0 );
            }

            if ( self _meth_8041() )
            {
                var_27 = self _meth_803A();

                if ( _id_09D1::_id_28F0( var_27, var_26 ) )
                    var_22 = _id_09D1::_id_28F6( 20, "defend_force_node_recalculation" );
            }

            if ( var_22 == "goal" )
            {
                if ( var_14 )
                    self _meth_805A( self._id_410C );

                childthread _id_4609();

                if ( var_21 && _id_09D1::_id_27E5() && !isplayer( var_0 ) && isdefined( self._id_45BA ) )
                    _id_09CE::_id_28E4();
            }
        }

        if ( var_22 != "goal" )
        {
            var_28 = 0.25;

            if ( var_22 == "no_path" && isdefined( self._id_45C3 ) )
                var_28 = self._id_45C3;

            wait( var_28 );
            continue;
        }

        var_29 = randomfloatrange( var_19, var_20 );
        var_22 = scripts\engine\utility::_id_108A9( var_29, "node_relinquished", "goal_changed", "script_goal_changed", "defend_force_node_recalculation", "bad_path" );

        if ( ( var_22 == "node_relinquished" || var_22 == "bad_path" || var_22 == "goal_changed" || var_22 == "script_goal_changed" ) && ( self._id_410C == "crouch" || self._id_410C == "prone" ) )
            self _meth_805A( "none" );

        if ( var_22 == "timeout" && !var_16 )
            _id_09D1::_id_28F7();
    }
}

_id_2EA9( var_0, var_1 )
{
    var_2 = "stand";

    if ( var_0 )
    {
        var_3 = 100;
        var_4 = 0;
        var_5 = 0;
        var_6 = self _meth_802F( "strategyLevel" );

        if ( var_6 == 1 )
        {
            var_3 = 20;
            var_4 = 25;
            var_5 = 55;
        }
        else if ( var_6 >= 2 )
        {
            var_3 = 10;
            var_4 = 20;
            var_5 = 70;
        }

        var_7 = randomint( 100 );

        if ( var_7 < var_4 )
            var_2 = "crouch";
        else if ( var_7 < var_4 + var_5 )
            var_2 = "prone";

        var_8 = !isdefined( var_1 ) || !var_1;

        if ( var_8 && var_2 == "prone" )
        {
            var_9 = _id_273C( "prone" );
            var_10 = _id_45BC( "prone" );

            if ( var_10.size >= var_9.size )
                var_2 = "crouch";
        }

        if ( var_8 && var_2 == "crouch" )
        {
            var_11 = _id_273C( "crouch" );
            var_12 = _id_45BC( "crouch" );

            if ( var_12.size >= var_11.size )
                var_2 = "stand";
        }
    }

    return var_2;
}

_id_DAD6( var_0 )
{
    var_1 = 1250;
    var_2 = var_1 * var_1;

    if ( var_0 )
    {
        if ( self _meth_802F( "strategyLevel" ) == 0 )
            return 0;

        if ( self._id_2749 == "capture_zone" && self _meth_81EF( self._id_2748 ) )
            return 0;

        return distancesquared( self.origin, self._id_2744 ) > var_2 * 0.75 * 0.75;
    }
    else if ( self _meth_804E() && distancesquared( self.origin, self._id_2744 ) < var_2 )
    {
        var_3 = self _meth_8038();
        return 0 <= var_3 && var_3 <= var_1;
    }
    else
        return 0;
}

_id_D7CB( var_0, var_1 )
{
    var_2 = spawnstruct();

    if ( isdefined( var_1 ) )
        var_2.origin = var_1;
    else
        var_2.origin = var_0.origin;

    var_2._id_02CD = var_0;
    var_2._id_5F1C = 0;
    return var_2;
}

_id_4600()
{
    self notify( "defense_cautious_approach" );
    self endon( "defense_cautious_approach" );
    level endon( "game_ended" );
    self endon( "defend_force_node_recalculation" );
    self endon( "death_or_disconnect" );
    self endon( "defend_stop" );
    self endon( "started_bot_defend_think" );

    if ( ![[ level._id_2777["should_start_cautious_approach"] ]]( 1 ) )
        return;

    var_0 = self _meth_803A();
    var_1 = self _meth_803B();
    var_2 = 1;
    var_3 = 0.2;
    var_4 = 0;

    while ( var_2 )
    {
        wait 0.25;
        var_4 = var_4 + 0.25;

        if ( !self _meth_8041() )
            return;

        var_5 = self _meth_803A();

        if ( !_id_09D1::_id_28F0( var_0, var_5 ) )
            return;

        if ( var_4 >= 1.0 )
        {
            var_6 = self _meth_8036();

            if ( var_6.size == 0 )
            {
                self _meth_802A();
                return;
            }
        }

        var_3 = var_3 + 0.25;

        if ( var_3 >= 0.5 )
        {
            var_3 = 0.0;

            if ( [[ level._id_2777["should_start_cautious_approach"] ]]( 0 ) )
                var_2 = 0;
        }
    }

    self _meth_8050( 1.8 );
    self _meth_8053( "cautious", 1 );
    var_7 = self _meth_8036();

    if ( !isdefined( var_7 ) || var_7.size <= 2 )
        return;

    self._id_96C8 = [];
    var_8 = 1000;

    if ( isdefined( level._id_BDB1 ) )
        var_8 = level._id_BDB1;

    var_9 = var_8 * var_8;
    var_10 = _func_00B4( self._id_2744, var_8, 0, 500 );

    if ( var_10.size <= 0 )
        return;

    var_11 = 5 + self _meth_802F( "strategyLevel" ) * 2;
    var_12 = int( min( var_11, var_10.size ) );
    var_13 = self _meth_8049( var_10, 15, var_12, "node_protect", _id_09D1::_id_45C2(), "ignore_occupancy" );

    for ( var_14 = 0; var_14 < var_13.size; var_14++ )
    {
        var_15 = _id_D7CB( var_13[var_14] );
        self._id_96C8 = scripts\engine\utility::array_add( self._id_96C8, var_15 );
    }

    var_16 = _func_0021( 0, gettime() - 60000, 1, "death", 0, self );

    foreach ( var_18 in var_16 )
    {
        if ( distancesquared( var_18, self._id_2744 ) < var_9 )
        {
            var_19 = _func_0080( var_18 );

            if ( isdefined( var_19 ) )
            {
                var_15 = _id_D7CB( var_19, var_18 );
                self._id_96C8 = scripts\engine\utility::array_add( self._id_96C8, var_15 );
            }
        }
    }

    if ( isdefined( self._id_45BA ) )
    {
        var_21 = _id_09D1::_id_2797( "stand", self._id_45BA );

        for ( var_14 = 0; var_14 < var_21.size; var_14++ )
        {
            var_15 = _id_D7CB( var_21[var_14] );
            self._id_96C8 = scripts\engine\utility::array_add( self._id_96C8, var_15 );
        }
    }

    if ( self._id_96C8.size == 0 )
        return;

    childthread _id_A0AF();
    var_22 = self _meth_803D();
    var_23 = self _meth_803C();
    var_24 = self _meth_803E();
    wait 0.05;

    for ( var_25 = 1; var_25 < var_7.size - 2; var_25++ )
    {
        _id_09D1::_id_28F7();
        var_26 = _func_00A6( var_7[var_25] );

        if ( var_26.size == 0 )
            continue;

        var_27 = [];

        for ( var_14 = 0; var_14 < var_26.size; var_14++ )
        {
            if ( !scripts\engine\utility::_id_10E74( self.origin, self getplayerangles(), var_26[var_14].origin, 0 ) )
                continue;

            for ( var_28 = 0; var_28 < self._id_96C8.size; var_28++ )
            {
                var_18 = self._id_96C8[var_28];

                if ( _func_0156( var_18._id_02CD, var_26[var_14], 1 ) )
                {
                    var_27 = scripts\engine\utility::array_add( var_27, var_26[var_14] );
                    var_28 = self._id_96C8.size;
                }
            }
        }

        if ( var_27.size == 0 )
            continue;

        var_29 = self _meth_8048( var_27, 1 + var_27.size * 0.15, "node_hide" );

        if ( isdefined( var_29 ) )
        {
            var_30 = [];

            for ( var_14 = 0; var_14 < self._id_96C8.size; var_14++ )
            {
                if ( _func_0156( self._id_96C8[var_14]._id_02CD, var_29, 1 ) )
                {
                    if ( distance2dsquared( self._id_96C8[var_14].origin, var_29.origin ) > 3600 )
                        var_30 = scripts\engine\utility::array_add( var_30, self._id_96C8[var_14] );
                }
            }

            self _meth_802A();
            self _meth_8058( var_29, "critical" );
            childthread _id_A0B0();
            var_31 = _id_09D1::_id_28F6( undefined, "cautious_approach_early_out" );
            self notify( "stop_cautious_approach_early_out_monitor" );

            if ( var_31 == "cautious_approach_early_out" )
                break;

            if ( var_31 == "goal" )
            {
                for ( var_14 = 0; var_14 < var_30.size; var_14++ )
                {
                    if ( distance2dsquared( self.origin, var_30[var_14].origin ) < 1600 )
                        continue;

                    for ( var_4 = 0; var_30[var_14]._id_5F1C < 18 && var_4 < 3.6; var_4 = var_4 + 0.25 )
                    {
                        self _meth_8044( var_30[var_14].origin + ( 0, 0, self _meth_8172() ), 0.25, "script_search" );
                        wait 0.25;
                    }
                }
            }
        }

        wait 0.05;
    }

    self notify( "stop_location_monitoring" );
    self _meth_802A();

    if ( isdefined( var_1 ) )
        self _meth_8058( var_1, var_22, var_24 );
    else
        self _meth_8057( self._id_410B, var_23, var_22, var_24 );
}

_id_A0B0()
{
    self endon( "cautious_approach_early_out" );
    self endon( "stop_cautious_approach_early_out_monitor" );
    var_0 = undefined;

    if ( isdefined( self._id_2747 ) )
        var_0 = self._id_2747 * self._id_2747;
    else if ( isdefined( self._id_2745 ) )
    {
        var_1 = _id_2705();
        var_0 = var_1 * var_1;
    }

    wait 0.05;

    for (;;)
    {
        if ( distancesquared( self.origin, self._id_2744 ) < var_0 )
            self notify( "cautious_approach_early_out" );

        wait 0.05;
    }
}

_id_A0AF()
{
    self endon( "stop_location_monitoring" );
    var_0 = 10000;

    for (;;)
    {
        var_1 = self _meth_815E();

        if ( isdefined( var_1 ) )
        {
            var_2 = self _meth_8031();

            for ( var_3 = 0; var_3 < self._id_96C8.size; var_3++ )
            {
                if ( _func_0156( var_1, self._id_96C8[var_3]._id_02CD, 1 ) )
                {
                    var_4 = scripts\engine\utility::_id_10E74( self.origin, self getplayerangles(), self._id_96C8[var_3].origin, var_2 );
                    var_5 = !var_4 || self._id_96C8[var_3]._id_5F1C < 17;

                    if ( var_5 && distancesquared( self.origin, self._id_96C8[var_3].origin ) < var_0 )
                    {
                        var_4 = 1;
                        self._id_96C8[var_3]._id_5F1C = 18;
                    }

                    if ( var_4 )
                    {
                        self._id_96C8[var_3]._id_5F1C++;

                        if ( self._id_96C8[var_3]._id_5F1C >= 18 )
                        {
                            self._id_96C8[var_3] = self._id_96C8[self._id_96C8.size - 1];
                            self._id_96C8[self._id_96C8.size - 1] = undefined;
                            var_3--;
                        }
                    }
                }
            }
        }

        wait 0.05;
    }
}

_id_BDB2()
{
    self notify( "protect_watch_allies" );
    self endon( "protect_watch_allies" );
    var_0 = [];
    var_1 = 1050;
    var_2 = var_1 * var_1;
    var_3 = 900;

    if ( isdefined( level._id_BDB1 ) )
        var_3 = level._id_BDB1;

    for (;;)
    {
        var_4 = gettime();
        var_5 = _id_27B0( self._id_2744, var_3 );

        foreach ( var_7 in var_5 )
        {
            var_8 = var_7._id_54E1;

            if ( !isdefined( var_8 ) )
                var_8 = var_7 getentitynumber();

            if ( !isdefined( var_0[var_8] ) )
                var_0[var_8] = var_4 - 1;

            if ( !isdefined( var_7._id_8F1B ) )
                var_7._id_8F1B = var_4 - 10001;

            if ( var_7.health == 0 && isdefined( var_7._id_43FE ) && var_4 - var_7._id_43FE < 5000 )
            {
                if ( var_4 - var_7._id_8F1B > 10000 && var_4 > var_0[var_8] )
                {
                    if ( isdefined( var_7._id_0251 ) && isdefined( var_7._id_0251.team ) && var_7._id_0251.team == scripts\engine\utility::_id_6460( self.team ) )
                    {
                        if ( distancesquared( var_7._id_25A4.origin, self.origin ) < var_2 )
                        {
                            self _meth_8033( var_7._id_0251, var_7._id_25A4.origin );
                            var_9 = _func_0080( var_7._id_25A4.origin );

                            if ( isdefined( var_9 ) )
                            {
                                self._id_4604 = var_9.origin;
                                self notify( "defend_force_node_recalculation" );
                            }

                            var_7._id_8F1B = var_4;
                        }

                        var_0[var_8] = var_4 + 10000;
                    }
                }
            }
        }

        wait( ( randomint( 5 ) + 1 ) * 0.05 );
    }
}

_id_4603()
{
    if ( isdefined( self._id_4606 ) )
        return self._id_4606;
    else if ( _id_09D1::_id_27DB() )
        return _id_273C( self._id_410C, 1 );
    else if ( _id_09D1::_id_27E5() || _id_09D1::_id_27DA() )
    {
        var_0 = _func_0066( self.origin );
        return var_0;
    }
}

_id_4609()
{
    self notify( "defense_watch_entrances_at_goal" );
    self endon( "defense_watch_entrances_at_goal" );
    self endon( "new_defend_goal" );
    self endon( "script_goal_changed" );
    var_0 = self _meth_815E();
    var_1 = undefined;

    if ( _id_09D1::_id_27DB() )
    {
        var_2 = _id_4603();
        var_1 = [];

        if ( isdefined( var_0 ) )
        {
            foreach ( var_4 in var_2 )
            {
                if ( _func_0156( var_0, var_4, 1 ) )
                    var_1 = scripts\engine\utility::array_add( var_1, var_4 );
            }
        }

        if ( var_1.size == 0 )
            var_1 = _func_0066( self.origin );
    }
    else if ( _id_09D1::_id_27E5() || _id_09D1::_id_27DA() )
    {
        var_1 = _id_4603();
        var_6 = self getcurrentweapon();

        if ( isdefined( var_0 ) && !issubstr( var_6.basename, "riotshield" ) && isdefined( self._id_A53D ) )
        {
            if ( _func_0156( var_0, self._id_A53D, 1 ) )
                var_1 = scripts\engine\utility::array_add( var_1, self._id_A53D );
        }
    }

    if ( isdefined( var_1 ) )
    {
        childthread _id_09D1::_id_28FF( var_1 );

        if ( _id_09D1::_id_27DA() )
            childthread _id_2837();
        else if ( isdefined( level._id_2777["bot_entrance_update"] ) )
            self childthread [[ level._id_2777["bot_entrance_update"] ]]();
        else
            childthread _id_2836();
    }
}

_id_2836()
{
    self notify( "bot_monitor_watch_entrances_at_goal" );
    self endon( "bot_monitor_watch_entrances_at_goal" );
    self notify( "bot_monitor_watch_entrances" );
    self endon( "bot_monitor_watch_entrances" );
    self endon( "bot_watch_nodes_stop" );

    while ( !isdefined( self._id_10A75 ) )
        wait 0.05;

    var_0 = level._id_2777["get_watch_node_chance"];

    for (;;)
    {
        var_1 = 0.8;
        var_2 = 1.0;

        if ( scripts\engine\utility::array_contains( self._id_4607, "strict_los" ) )
        {
            var_1 = 1.0;
            var_2 = 0.5;
        }

        if ( isdefined( self._id_A53D ) )
        {
            foreach ( var_4 in self._id_10A75 )
            {
                if ( var_4 == self._id_A53D )
                {
                    var_4._id_10A73[self._id_54E1] = var_4._id_10A72[self._id_54E1] * var_1;
                    continue;
                }

                var_4._id_10A73[self._id_54E1] = var_4._id_10A72[self._id_54E1] * var_2;
            }
        }

        var_6 = isdefined( var_0 );

        if ( !var_6 )
            _id_BD18( 0.5 );

        foreach ( var_4 in self._id_10A75 )
        {
            if ( var_6 )
            {
                var_8 = self [[ var_0 ]]( var_4 );
                var_4._id_10A73[self._id_54E1] = var_4._id_10A73[self._id_54E1] * var_8;
            }

            if ( _id_5501( var_4 ) )
                var_4._id_10A73[self._id_54E1] = var_4._id_10A73[self._id_54E1] * 0.5;
        }

        wait( randomfloatrange( 0.5, 0.75 ) );
    }
}

_id_2837()
{
    self notify( "bot_monitor_watch_entrances_bodyguard" );
    self endon( "bot_monitor_watch_entrances_bodyguard" );
    self notify( "bot_monitor_watch_entrances" );
    self endon( "bot_monitor_watch_entrances" );

    while ( !isdefined( self._id_10A75 ) )
        wait 0.05;

    for (;;)
    {
        var_0 = anglestoforward( self._id_273E getplayerangles() ) * ( 1, 1, 0 );
        var_0 = vectornormalize( var_0 );

        foreach ( var_2 in self._id_10A75 )
        {
            var_2._id_10A73[self._id_54E1] = var_2._id_10A72[self._id_54E1];
            var_3 = var_2.origin - self._id_273E.origin;
            var_3 = vectornormalize( var_3 );
            var_4 = vectordot( var_0, var_3 );

            if ( var_4 > 0.6 )
                var_2._id_10A73[self._id_54E1] = var_2._id_10A73[self._id_54E1] * 0.33;
            else if ( var_4 > 0 )
                var_2._id_10A73[self._id_54E1] = var_2._id_10A73[self._id_54E1] * 0.66;

            if ( !_id_54FF( var_2 ) )
                var_2._id_10A73[self._id_54E1] = var_2._id_10A73[self._id_54E1] * 0.5;
        }

        wait( randomfloatrange( 0.4, 0.6 ) );
    }
}

_id_54FF( var_0 )
{
    var_1 = _func_00B8( var_0 );
    var_2 = vectornormalize( var_0.origin - self.origin );

    for ( var_3 = 0; var_3 < level._id_110DF; var_3++ )
    {
        if ( _func_0029( var_3, self.team, "enemy_predict" ) > 0 )
        {
            if ( isdefined( var_1 ) && var_3 == var_1 )
                return 1;
            else
            {
                var_4 = vectornormalize( _func_00F9( var_3 ) - self.origin );
                var_5 = vectordot( var_2, var_4 );

                if ( var_5 > 0.2 )
                    return 1;
            }
        }
    }

    return 0;
}

_id_BD18( var_0 )
{
    if ( self._id_10A75.size <= 0 )
        return;

    var_1 = self._id_10A75;

    for ( var_2 = 0; var_2 < level._id_110DF; var_2++ )
    {
        if ( _func_0029( var_2, self.team, "enemy_predict" ) <= 0 )
            continue;

        if ( var_1.size == 0 )
            break;

        var_3 = vectornormalize( _func_00F9( var_2 ) - self.origin );

        for ( var_4 = 0; var_4 < var_1.size; var_4++ )
        {
            var_5 = _func_00B8( var_1[var_4] );
            var_6 = 0;

            if ( isdefined( var_5 ) && var_2 == var_5 )
                var_6 = 1;
            else
            {
                var_7 = vectornormalize( var_1[var_4].origin - self.origin );
                var_8 = vectordot( var_7, var_3 );

                if ( var_8 > 0.2 )
                    var_6 = 1;
            }

            if ( var_6 )
            {
                var_1[var_4]._id_10A73[self._id_54E1] = var_1[var_4]._id_10A73[self._id_54E1] * var_0;
                var_1[var_4] = var_1[var_1.size - 1];
                var_1[var_1.size - 1] = undefined;
                var_4--;
            }
        }
    }
}

_id_5501( var_0 )
{
    if ( self._id_2749 == "protect_zone" )
        var_1 = _id_27AF( self._id_274A );
    else
        var_1 = _id_27AE( self._id_2744 );

    foreach ( var_3 in var_1 )
    {
        if ( _id_5502( var_3, var_0 ) )
            return 1;
    }

    return 0;
}

_id_5502( var_0, var_1 )
{
    var_2 = anglestoforward( var_0 getplayerangles() );
    var_3 = vectornormalize( var_1.origin - var_0.origin );
    var_4 = vectordot( var_2, var_3 );

    if ( var_4 > 0.6 )
        return 1;

    return 0;
}

_id_27AF( var_0 )
{
    var_1 = [];
    var_2 = _id_27B0( self.origin, 1000 );

    foreach ( var_4 in var_2 )
    {
        if ( !isai( var_4 ) || var_4 _id_09D1::_id_27DF() && var_4._id_274A == var_0 )
            var_1 = scripts\engine\utility::array_add( var_1, var_4 );
    }

    return var_1;
}

_id_27AE( var_0, var_1 )
{
    if ( !isdefined( var_1 ) )
    {
        if ( isdefined( level._id_BDB1 ) )
            var_1 = level._id_BDB1;
        else
            var_1 = 900;
    }

    var_2 = [];
    var_3 = _id_27B0( var_0, var_1 );

    foreach ( var_5 in var_3 )
    {
        if ( !isai( var_5 ) || var_5 _id_09D1::_id_27E0( var_0 ) )
            var_2 = scripts\engine\utility::array_add( var_2, var_5 );
    }

    return var_2;
}

_id_27B0( var_0, var_1 )
{
    var_2 = var_1 * var_1;
    var_3 = [];

    for ( var_4 = 0; var_4 < level._id_AE69.size; var_4++ )
    {
        var_5 = level._id_AE69[var_4];

        if ( var_5 != self && isdefined( var_5.team ) && var_5.team == self.team && _id_0A67::_id_8A7B( var_5 ) )
        {
            if ( distancesquared( var_0, var_5.origin ) < var_2 )
                var_3 = scripts\engine\utility::array_add( var_3, var_5 );
        }
    }

    return var_3;
}

_id_4601()
{
    level endon( "game_ended" );
    self endon( "started_bot_defend_think" );
    self endon( "defend_stop" );
    self endon( "disconnect" );
    self waittill( "death" );

    if ( isdefined( self ) )
        thread _id_2740();
}

_id_2740()
{
    self notify( "defend_stop" );
    self._id_2743 = undefined;
    self._id_2744 = undefined;
    self._id_2747 = undefined;
    self._id_2745 = undefined;
    self._id_2749 = undefined;
    self._id_2748 = undefined;
    self._id_2746 = undefined;
    self._id_273E = undefined;
    self._id_274A = undefined;
    self._id_4607 = undefined;
    self._id_A53D = undefined;
    self._id_4604 = undefined;
    self._id_4602 = undefined;
    self._id_45BF = undefined;
    self._id_BBF8 = undefined;
    self._id_410A = undefined;
    self._id_4109 = undefined;
    self._id_410B = undefined;
    self._id_45BA = undefined;
    self._id_4606 = undefined;
    self _meth_802A();
    self _meth_805A( "none" );
}

_id_45BC( var_0 )
{
    var_1 = [];

    foreach ( var_3 in level._id_AE69 )
    {
        if ( !isdefined( var_3.team ) )
            continue;

        if ( var_3.team == self.team && var_3 != self && isai( var_3 ) && var_3 _id_09D1::_id_27DF() && isdefined( var_3._id_410C ) && var_3._id_410C == var_0 )
        {
            if ( var_3._id_2749 == self._id_2749 && _id_09D1::_id_27E0( var_3._id_2744 ) )
                var_1 = scripts\engine\utility::array_add( var_1, var_3 );
        }
    }

    return var_1;
}

_id_A0B3()
{
    var_0 = 0;
    var_1 = 175;
    var_2 = self._id_273E.origin;
    var_3 = 0;
    var_4 = 0;

    for (;;)
    {
        if ( !isdefined( self._id_273E ) )
            thread _id_2740();

        self._id_2744 = self._id_273E.origin;
        self._id_A53D = self._id_273E _meth_815E();

        if ( !isdefined( self._id_A53D ) )
            self._id_A53D = self _meth_815E();

        if ( self _meth_803D() != "none" )
        {
            var_5 = self _meth_803A();
            var_6 = self._id_273E getvelocity();
            var_7 = _func_0133( var_6 );

            if ( var_7 > 100 )
            {
                var_0 = 0;

                if ( distancesquared( var_2, self._id_273E.origin ) > var_1 * var_1 )
                {
                    var_2 = self._id_273E.origin;
                    var_4 = 1;
                    var_8 = vectornormalize( var_5 - self._id_273E.origin );
                    var_9 = vectornormalize( var_6 );

                    if ( vectordot( var_8, var_9 ) < 0.1 )
                    {
                        self notify( "defend_force_node_recalculation" );
                        wait 0.25;
                    }
                }
            }
            else
            {
                var_0 = var_0 + 0.05;

                if ( var_3 > 100 && var_4 )
                {
                    var_2 = self._id_273E.origin;
                    var_4 = 0;
                }

                if ( var_0 > 0.5 )
                {
                    var_10 = distancesquared( var_5, self._id_2744 );

                    if ( var_10 > self._id_2747 * self._id_2747 )
                    {
                        self notify( "defend_force_node_recalculation" );
                        wait 0.25;
                    }
                }
            }

            var_3 = var_7;

            if ( abs( self._id_273E.origin[2] - var_5[2] ) >= 50 )
            {
                self notify( "defend_force_node_recalculation" );
                wait 0.25;
            }
        }

        wait 0.05;
    }
}

_id_5AA1()
{
    var_0 = _id_273D();
    var_1 = _id_09D1::_id_276B( _id_09D1::_id_45C2(), self._id_2747, var_0 );

    if ( isdefined( var_1 ) )
    {
        if ( isdefined( var_0 ) )
        {
            var_2 = vectornormalize( var_0 - var_1.origin );
            self._id_4109 = vectortoangles( var_2 );
        }
        else
        {
            var_3 = vectornormalize( var_1.origin - _id_09D1::_id_45C2() );
            self._id_4109 = vectortoangles( var_3 );
        }

        self._id_410A = var_1;
    }
    else if ( isdefined( var_0 ) )
        _id_27C1( var_0, undefined );
    else
        _id_27C1( undefined, _id_09D1::_id_45C2() );
}

_id_5AA2()
{
    var_0 = _id_273D();
    var_1 = _id_09D1::_id_276C( self._id_2745, var_0 );

    if ( isdefined( var_1 ) )
    {
        if ( isdefined( var_0 ) )
        {
            var_2 = vectornormalize( var_0 - var_1.origin );
            self._id_4109 = vectortoangles( var_2 );
        }
        else
        {
            var_3 = vectornormalize( var_1.origin - _id_09D1::_id_45C2() );
            self._id_4109 = vectortoangles( var_3 );
        }

        self._id_410A = var_1;
    }
    else if ( isdefined( var_0 ) )
        _id_27C1( var_0, undefined );
    else
        _id_27C1( undefined, _id_09D1::_id_45C2() );
}

_id_5AA4()
{
    var_0 = _id_09D1::_id_276A( _id_09D1::_id_45C2(), self._id_2747 );

    if ( isdefined( var_0 ) )
    {
        var_1 = vectornormalize( _id_09D1::_id_45C2() - var_0.origin );
        self._id_4109 = vectortoangles( var_1 );
        self._id_410A = var_0;
    }
    else
        _id_27C1( _id_09D1::_id_45C2(), undefined );
}

_id_5AA5()
{
    var_0 = _id_09D1::_id_276E( self._id_2745, _id_09D1::_id_45C2() );

    if ( isdefined( var_0 ) )
        self._id_410A = var_0;
    else
        _id_27C1( _id_09D1::_id_45C2(), undefined );
}

_id_5AA0()
{
    var_0 = _id_09D1::_id_276D( _id_09D1::_id_45C2(), self._id_2747 );

    if ( isdefined( var_0 ) )
        self._id_410A = var_0;
    else
    {
        var_1 = self _meth_815E();

        if ( isdefined( var_1 ) )
            self._id_410A = var_1;
        else
            self._id_410B = self.origin;
    }
}

_id_5AA3()
{
    var_0 = undefined;
    var_1 = _func_00B4( _id_09D1::_id_45C2(), self._id_2747, 0 );

    if ( isdefined( var_1 ) && var_1.size > 0 )
        var_0 = self _meth_8048( var_1, 1 + var_1.size * 0.5, "node_traffic" );

    if ( isdefined( var_0 ) )
        self._id_410A = var_0;
    else
        _id_27C1( undefined, _id_09D1::_id_45C2() );
}

_id_27C1( var_0, var_1 )
{
    if ( self._id_2749 == "protect_zone" )
        self._id_410B = scripts\engine\utility::random( self._id_2745 ).origin;
    else
    {
        if ( self._id_2749 == "capture_zone" )
            self._id_410B = _id_09D1::_id_2864( _id_09D1::_id_45C2(), self._id_2745, ::_id_2700 );
        else
            self._id_410B = _id_09D1::_id_2865( _id_09D1::_id_45C2(), self._id_2747, ::_id_2700, 0.15, 0.9 );

        if ( isdefined( var_0 ) )
        {
            var_2 = vectornormalize( var_0 - self._id_410B );
            self._id_4109 = vectortoangles( var_2 );
            return;
        }

        if ( isdefined( var_1 ) )
        {
            var_2 = vectornormalize( self._id_410B - var_1 );
            self._id_4109 = vectortoangles( var_2 );
        }
    }
}

_id_2700( var_0 )
{
    if ( _id_2707( var_0, 1, 1, 1 ) )
        return 0;

    return 1;
}

_id_2707( var_0, var_1, var_2, var_3 )
{
    for ( var_4 = 0; var_4 < level._id_AE69.size; var_4++ )
    {
        var_5 = level._id_AE69[var_4];

        if ( var_5.team == self.team && var_5 != self )
        {
            if ( isai( var_5 ) )
            {
                if ( var_2 )
                {
                    if ( distancesquared( var_0, var_5.origin ) < 441 )
                        return 1;
                }

                if ( var_3 && var_5 _meth_8041() )
                {
                    var_6 = var_5 _meth_803A();

                    if ( distancesquared( var_0, var_6 ) < 441 )
                        return 1;
                }

                continue;
            }

            if ( var_1 )
            {
                if ( distancesquared( var_0, var_5.origin ) < 441 )
                    return 1;
            }
        }
    }

    return 0;
}

_id_2705()
{
    var_0 = 0;

    if ( isdefined( self._id_2745 ) )
    {
        foreach ( var_2 in self._id_2745 )
        {
            var_3 = distance( self._id_2744, var_2.origin );
            var_0 = max( var_3, var_0 );
        }
    }

    return var_0;
}

_id_28DC()
{
    self notify( "bot_think_tactical_goals" );
    self endon( "bot_think_tactical_goals" );
    self endon( "death_or_disconnect" );
    level endon( "game_ended" );
    self._id_ED26 = [];
    self._id_ED25 = 0;

    for (;;)
    {
        if ( self._id_ED26.size > 0 && !_id_09D1::_id_27E9() )
        {
            var_0 = self._id_ED26[0];

            if ( !isdefined( var_0._id_0DDD ) )
            {
                self notify( "start_tactical_goal" );

                if ( isdefined( var_0._id_E653 ) )
                    self [[ var_0._id_E653 ]]( var_0 );

                childthread _id_10A6F( var_0 );
                var_1 = "tactical";

                if ( isdefined( var_0._id_7063 ) )
                    var_1 = var_0._id_7063;

                if ( istrue( var_0._id_38D6 ) )
                    self _meth_802A();

                self _meth_8057( var_0._id_7061, var_0._id_7062, var_1, var_0._id_01E4, var_0._id_A895, var_0._id_DA3B );
                var_2 = _id_09D1::_id_28F6( undefined, "stop_tactical_goal" );
                self notify( "stop_goal_aborted_watch" );

                if ( var_2 == "goal" )
                {
                    if ( isdefined( var_0._id_0E5D ) )
                    {
                        self._id_ED25 = 1;
                        self [[ var_0._id_0E5D ]]( var_0 );
                        self._id_ED25 = 0;
                    }
                }

                if ( var_2 != "script_goal_changed" )
                    self _meth_802A();

                if ( isdefined( var_0._id_52AD ) )
                    self [[ var_0._id_52AD ]]( var_0 );
            }

            self._id_ED26 = scripts\engine\utility::array_remove( self._id_ED26, var_0 );
        }

        wait 0.05;
    }
}

_id_10A6F( var_0 )
{
    self endon( "stop_tactical_goal" );
    self endon( "stop_goal_aborted_watch" );
    wait 0.05;

    for (;;)
    {
        if ( isdefined( var_0._id_0DDD ) || isdefined( var_0._id_DA69 ) && self [[ var_0._id_DA69 ]]( var_0 ) )
            self notify( "stop_tactical_goal" );

        wait 0.05;
    }
}

_id_283C( var_0, var_1, var_2, var_3 )
{
    if ( _func_0133( var_1 ) == 0 )
        var_1 = var_1 + ( 0, 0, 1 );

    var_4 = spawnstruct();
    var_4._id_048F = var_0;
    var_4._id_7061 = var_1;

    if ( isdefined( self._id_AB1B ) )
    {
        if ( !scripts\engine\utility::array_contains( self._id_AB1B, var_0 ) )
            return;
    }

    var_4._id_BD19 = var_2;
    var_4._id_A84D = var_3._id_A84D;
    var_4._id_7063 = var_3._id_CD66;
    var_4._id_01E4 = var_3._id_CD67;
    var_4._id_7062 = 0;

    if ( isdefined( var_3._id_CD65 ) )
        var_4._id_7062 = var_3._id_CD65;

    var_4._id_E653 = var_3._id_E653;
    var_4._id_52AD = var_3._id_52AD;
    var_4._id_DA69 = var_3._id_DA69;
    var_4._id_0E5D = var_3._id_0E5D;
    var_4._id_A895 = var_3._id_A895;
    var_4._id_DA3B = var_3._id_DA3B;
    var_4._id_AC39 = var_3._id_AC39;
    var_4._id_38D6 = var_3._id_38D6;

    for ( var_5 = 0; var_5 < self._id_ED26.size; var_5++ )
    {
        if ( var_4._id_BD19 > self._id_ED26[var_5]._id_BD19 )
            break;
    }

    for ( var_6 = self._id_ED26.size - 1; var_6 >= var_5; var_6-- )
        self._id_ED26[var_6 + 1] = self._id_ED26[var_6];

    self._id_ED26[var_5] = var_4;
}

_id_27C7( var_0, var_1 )
{
    if ( !isdefined( self._id_ED26 ) )
        return 0;

    if ( isdefined( var_0 ) )
    {
        foreach ( var_3 in self._id_ED26 )
        {
            if ( var_3._id_048F == var_0 )
            {
                if ( isdefined( var_1 ) && isdefined( var_3._id_A84D ) )
                    return var_3._id_A84D == var_1;
                else
                    return 1;
            }
        }

        return 0;
    }
    else
        return self._id_ED26.size > 0;
}

_id_278E( var_0 )
{
    var_1 = [];

    if ( isdefined( self._id_ED26 ) )
    {
        foreach ( var_3 in self._id_ED26 )
        {
            if ( !istrue( var_3._id_0DDD ) && var_3._id_048F == var_0 )
                var_1[var_1.size] = var_3;
        }
    }

    return var_1;
}

_id_26C9( var_0, var_1 )
{
    if ( !isdefined( self._id_ED26 ) )
        return;

    foreach ( var_3 in self._id_ED26 )
    {
        if ( var_3._id_048F == var_0 )
        {
            if ( isdefined( var_1 ) )
            {
                if ( isdefined( var_3._id_A84D ) && var_3._id_A84D == var_1 )
                    var_3._id_0DDD = 1;

                continue;
            }

            var_3._id_0DDD = 1;
        }
    }
}

_id_274F()
{
    self._id_AB1B[0] = "map_interactive_object";

    foreach ( var_1 in self._id_ED26 )
    {
        if ( var_1._id_048F != "map_interactive_object" )
            var_1._id_0DDD = 1;
    }
}

_id_275C()
{
    self._id_AB1B = undefined;
}

_id_282F()
{
    var_0 = gettime();

    if ( !isdefined( self._id_8F24 ) || var_0 - self._id_8F24 > 1000 )
    {
        self._id_8F24 = var_0;
        var_1 = _id_2790( "tacticalinsertion" );

        if ( !isdefined( var_1 ) )
            return 0;

        if ( isdefined( self._id_017D ) && self _meth_8027( self._id_017D ) )
            return 0;

        var_2 = _func_00F5( self.origin );

        if ( !isdefined( var_2 ) )
            return 0;

        var_3 = _func_002B( var_2, self.team, 1, "enemy_predict", ">", 0 );

        if ( !isdefined( var_3 ) )
            return 0;

        var_4 = _func_00B4( self.origin, 500, 0 );

        if ( var_4.size <= 0 )
            return 0;

        var_5 = self _meth_8048( var_4, var_4.size * 0.15, "node_hide" );

        if ( !isdefined( var_5 ) )
            return 0;

        return _id_289B( var_1, undefined, undefined, undefined, var_5 );
    }

    return 0;
}
