// S4 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

_id_93E6()
{
    scripts\cp_mp\utility\script_utility::registersharedfunc( "light_tank", "activate", ::_id_93D6 );
    scripts\cp_mp\utility\script_utility::registersharedfunc( "light_tank", "startCapture", ::_id_93F8 );
    scripts\cp_mp\utility\script_utility::registersharedfunc( "light_tank", "endCapture", ::_id_93E2 );
    scripts\cp_mp\utility\script_utility::registersharedfunc( "light_tank", "filterDropSpawns", ::_id_93E3 );
    scripts\cp_mp\utility\script_utility::registersharedfunc( "light_tank", "getDropSpawnIgnoreList", ::_id_93E4 );
    scripts\cp_mp\utility\script_utility::registersharedfunc( "light_tank", "spawnCallback", ::_id_93F7 );
    scripts\cp_mp\utility\script_utility::registersharedfunc( "light_tank", "initLate", ::_id_93E9 );
    scripts\cp_mp\vehicles\vehicle_tracking::_id_102C0( "light_tank", 6 );
    scripts\cp_mp\vehicles\vehicle_tracking::_id_102C2( "light_tank", 3 );
    _id_0A6E::_id_C27C( _id_09AD::_id_9419 );
    _id_93EA();
    _id_93EB();
    _id_93E7();
    scripts\mp\utility\killstreak::_id_10228( "light_tank", _id_09AD::_id_93AF );
}

_id_93E9()
{
    scripts\mp\killstreaks\killstreaks::_id_C25C( "bradley", _id_09AD::_id_940E );
}

_id_93EA()
{
    var_0 = _id_09B9::_id_10142( "light_tank", 1 );
    var_0._id_5FBD = 115;
    var_0._id_206B = 110;
    var_0._id_9183 = 60;
    var_0._id_C855 = 60;
    var_0._id_292E = 20;
    var_0._id_4B75 = 35;
}

_id_93EB()
{
    var_0 = scripts\cp_mp\vehicles\vehicle_spawn::_id_10274( "light_tank", 1 );
    var_0._id_0DD8 = _id_09AD::_id_940C;

    if ( scripts\mp\utility\game::getgametype() == "arm" )
    {
        var_0._id_0DD9 = 105;
        var_0._id_C691 = level._id_EE42;
    }
    else
        var_0._id_0DD9 = 40;
}

_id_93E7()
{
    scripts\mp\playeractions::_id_C22D( "vehicleCapture", [ "offhand_weapons", "weapon", "killstreaks", "supers" ] );
}

_id_93D6( var_0 )
{
    var_0 thread _id_243B();
    scripts\mp\utility\killstreak::_id_10227( var_0 );
}

_id_93F8( var_0, var_1, var_2 )
{
    if ( isdefined( var_1 ) )
        _id_93DC( var_0, var_1 );

    if ( level.teambased )
        _id_93DB( var_0 );
}

_id_93E2( var_0 )
{
    var_0 _id_93E0();
}

_id_93DC( var_0, var_1 )
{
    var_2 = scripts\cp_mp\vehicles\vehicle::_id_100CA( var_0, "tur_bradley_mp" );
    var_3 = spawn( "script_model", var_2 gettagorigin( "TAG_PLAYER" ) );
    var_3 linkto( var_2 );
    var_3 _id_93F5( 0.5 );
    var_3._id_FFF1 = var_0;
    var_0._id_AD8B = var_3;
    var_3 thread _id_93F0( var_1, var_0 );
    var_3 thread _id_93F1( var_1 );
    return var_3;
}

_id_93DB( var_0 )
{
    var_1 = scripts\cp_mp\vehicles\vehicle::_id_100CA( var_0, "tur_bradley_mp" );
    var_2 = spawn( "script_model", var_1 gettagorigin( "TAG_PLAYER" ) );
    var_2 linkto( var_1 );
    var_2 _id_93F5( 3 );
    var_2._id_FFF1 = var_0;
    var_0._id_AC88 = var_2;
    var_2 thread _id_93EE( var_0 );
    var_2 thread _id_93EF();
    return var_2;
}

_id_93F5( var_0 )
{
    self setcursorhint( "HINT_BUTTON" );

    if ( !scripts\cp_mp\utility\game_utility::_id_89D2() )
        self sethintstring( &"KILLSTREAKS_HINTS/BRADLEY_CAPTURE" );

    self _meth_84D6( "none" );
    self _meth_84D3( 200 );
    self sethintdisplayfov( 360 );
    self setuserange( 200 );
    self setusefov( 360 );
    self _meth_84D8( "show" );
    self setuseholdduration( "duration_none" );
    self hashed_0x84D0( 1 );
    self makeuseable();
    self._id_FEAF = 1;
    self._id_4122 = 0;
    self._id_FEE5 = var_0;
    self._id_84D5 = 0;
    self._id_B7FB = undefined;
    self._id_7C71 = "care_package";
}

_id_93DF()
{
    if ( isdefined( self._id_B7FB ) )
        _id_93F4( self._id_B7FB );

    self delete();
}

_id_93E0()
{
    if ( isdefined( self._id_AD8B ) )
        self._id_AD8B _id_93DF();

    if ( isdefined( self._id_AC88 ) )
        self._id_AC88 _id_93DF();
}

_id_93F0( var_0, var_1 )
{
    self endon( "death" );
    var_0 endon( "disconnect" );
    self._id_FFF1 = var_1;

    for (;;)
    {
        self waittillmatch( "trigger", var_0 );

        if ( _id_93D8( var_0 ) )
        {
            self._id_B7FB = var_0;
            self._id_84D5 = 1;
            _id_93F3( var_0 );
            var_2 = _id_93EC();
            self._id_B7FB = undefined;
            self._id_4122 = 0;
            self._id_84D5 = 0;
            _id_93F4( var_0 );

            if ( istrue( var_2 ) )
                thread _id_09AD::_id_938A( var_1, var_0 );

            waitframe();
        }
    }
}

_id_93EE( var_0 )
{
    self endon( "death" );

    for (;;)
    {
        self waittill( "trigger", var_1 );

        if ( _id_93D8( var_1 ) )
        {
            self._id_B7FB = var_1;
            self._id_84D5 = 1;
            _id_93F3( var_1 );
            var_2 = _id_93EC();
            self._id_B7FB = undefined;
            self._id_4122 = 0;
            self._id_84D5 = 0;

            if ( isdefined( var_1 ) )
                _id_93F4( var_1 );

            if ( istrue( var_2 ) )
                thread _id_09AD::_id_938A( var_0, var_1 );

            waitframe();
        }
    }
}

_id_93EC()
{
    self._id_B7FB endon( "death_or_disconnect" );

    while ( _id_93D7() )
    {
        self._id_4122 = self._id_4122 + level._id_5F1B * self._id_FEAF;

        if ( self._id_4122 >= self._id_FEE5 )
            return 1;

        self._id_B7FB _id_07AD::_id_FD73( self, 1 );
        waitframe();
    }
}

_id_93F1( var_0 )
{
    self endon( "death" );

    while ( isdefined( var_0 ) )
    {
        foreach ( var_2 in level.players )
        {
            self disableplayeruse( var_2 );

            if ( var_2 == var_0 )
            {
                if ( isdefined( self._id_B7FB ) )
                {
                    if ( _id_93D7() )
                        self _meth_80E0( var_0 );

                    continue;
                }

                if ( _id_93D8( var_0 ) )
                    self _meth_80E0( var_0 );
            }
        }

        wait 0.1;
    }

    thread _id_93DF();
}

_id_93EF()
{
    self endon( "death" );

    for (;;)
    {
        if ( isdefined( self._id_B7FB ) )
        {
            foreach ( var_1 in level.players )
            {
                self disableplayeruse( var_1 );

                if ( var_1 == self._id_B7FB )
                {
                    if ( _id_93D7() )
                        self _meth_80E0( var_1 );
                }
            }
        }
        else
        {
            foreach ( var_1 in level.players )
            {
                self disableplayeruse( var_1 );

                if ( _id_93D8( var_1 ) )
                    self _meth_80E0( var_1 );
            }
        }

        wait 0.1;
    }
}

_id_93D8( var_0 )
{
    if ( istrue( self._id_FFF1._id_87E1 ) )
        return 0;

    if ( !isdefined( var_0 ) )
        return 0;

    if ( !var_0 scripts\cp_mp\utility\player_utility::_id_0C14() )
        return 0;

    if ( var_0.team == "spectator" )
        return 0;

    if ( !var_0 scripts\common\utility::_id_86F6() )
        return 0;

    if ( !istrue( _id_09B8::_id_100FE( var_0, self._id_FFF1 ) ) )
        return 0;

    return 1;
}

_id_93D7()
{
    if ( istrue( self._id_FFF1._id_87E1 ) )
        return 0;

    if ( !self._id_B7FB scripts\common\utility::_id_86F6() )
        return 0;

    if ( !istrue( _id_09B8::_id_100FE( self._id_B7FB, self._id_FFF1 ) ) )
        return 0;

    if ( !self._id_B7FB usebuttonpressed() )
        return 0;

    if ( self._id_B7FB isonladder() )
        return 0;

    if ( self._id_B7FB meleebuttonpressed() )
        return 0;

    if ( distancesquared( self._id_B7FB.origin, self.origin ) > 90000 )
        return 0;

    return 1;
}

_id_93F3( var_0 )
{
    var_0 scripts\mp\playeractions::_id_156E( "vehicleCapture", 0 );
    var_0 _id_07AD::_id_FD73( self, 0 );
}

_id_93F4( var_0 )
{
    if ( var_0 scripts\cp_mp\utility\player_utility::_id_0C14() )
        var_0 scripts\mp\playeractions::_id_156E( "vehicleCapture", 1 );

    var_0 _id_07AD::_id_FD73( self, 0 );
}

_id_93F6( var_0, var_1 )
{
    if ( !isdefined( var_1 ) )
        return 0;

    if ( level.teambased && var_1.team == var_0.team )
        return 0;

    if ( isdefined( var_0.owner ) && var_1 == var_0.owner )
        return 0;

    return 1;
}

_id_243B()
{
    level endon( "game_ended" );
    self endon( "death" );

    for (;;)
    {
        if ( scripts\mp\utility\teams::_id_885E( self.team ) )
        {
            var_0 = scripts\common\utility::_id_B7AC( self.origin, 3000 );

            foreach ( var_2 in var_0 )
            {
                var_3 = isdefined( var_2 ) && var_2 scripts\cp_mp\utility\player_utility::_id_0C14() && scripts\mp\utility\player::isenemy( var_2 );

                if ( !var_3 )
                    continue;

                var_4 = anglestoforward( var_2 getplayerangles() );
                var_5 = scripts\engine\math::_id_1763( var_4, self.origin - var_2.origin );

                if ( isdefined( var_5 ) && var_5 <= 60 )
                {
                    if ( self _meth_83CC( var_2 geteye(), self ) > 0.1 )
                    {

                    }

                    waitframe();
                }
            }
        }

        wait 0.1;
    }
}

_id_93F7( var_0, var_1 )
{
    _id_09AD::_id_93C2( var_0 );

    if ( !isdefined( var_0._id_E322 ) )
        var_0._id_E322 = "place_at_position_unsafe";

    if ( !isdefined( var_0._id_DCAD ) )
        var_0._id_DCAD = 0;

    var_0._id_31D1 = 0;
    var_2 = _id_09AD::_id_9403( var_0, var_1 );

    if ( isdefined( var_2 ) && scripts\cp_mp\vehicles\vehicle_spawn::_id_10270() )
        var_2._id_AA96 = ::_id_93F2;

    return var_2;
}

_id_93F2()
{
    thread _id_93F9();
}

_id_93F9()
{
    var_0 = scripts\cp_mp\vehicles\vehicle_tracking::_id_6E22( self );
    var_1 = spawnstruct();
    scripts\cp_mp\vehicles\vehicle_tracking::_id_3D43( var_0, var_1 );
    _id_09AD::_id_938E( var_0, var_1 );
    var_2 = spawnstruct();
    var_3 = scripts\cp_mp\vehicles\vehicle_spawn::_id_1028E( "light_tank", var_1, var_2 );

    if ( isdefined( var_3 ) )
    {
        if ( scripts\mp\utility\game::getgametype() == "arm" )
        {
            if ( _id_07A8::_id_609F( "prematch_done" ) )
                scripts\mp\gametypes\arm::_id_504C( var_1 );

            if ( istrue( level._id_DCEE ) )
                scripts\mp\gametypes\arm::_id_10028( var_3, var_3.team );

            foreach ( var_5 in level.players )
            {
                if ( var_5.team == var_3.team )
                    var_5 _id_0A70::_id_D5DD( 62, undefined, 5 );
            }
        }
    }
}

_id_93E3( var_0 )
{
    var_1 = var_0;

    if ( isdefined( level._id_10396 ) )
    {
        var_1 = [];

        foreach ( var_3 in var_0 )
        {
            if ( _func_0119( var_3.origin, level._id_10396 ) )
                var_1[var_1.size] = var_3;
        }
    }

    return var_1;
}

_id_93E4( var_0 )
{
    var_1 = [];
    var_1[var_1.size] = var_0;

    if ( isdefined( level._id_77BE ) )
        var_1[var_1.size] = level._id_77BE;

    if ( isdefined( level._id_957C ) )
        var_1[var_1.size] = level._id_957C;

    if ( isdefined( level._id_EB97 ) )
        var_1[var_1.size] = level._id_EB97;

    var_1[var_1.size] = scripts\cp_mp\vehicles\vehicle_tracking::_id_102BA( "emp_drone" );
    var_1[var_1.size] = scripts\cp_mp\vehicles\vehicle_tracking::_id_102BA( "cruise_predator" );
    return scripts\engine\utility::_id_1B73( var_1 );
}
