// IW8 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

perk_getmeleescalar()
{
    if ( isdefined( self.perk_data["melee_scalar"] ) )
        return self.perk_data["melee_scalar"];
    else
        return self.perk_data["health"].melee_scalar;
}

perk_getmaxhealth()
{
    if ( isdefined( self.perk_data["max_health"] ) )
        return self.perk_data["max_health"];
    else
        return self.perk_data["health"].max_health;
}

perk_getbulletdamagescalar()
{
    if ( isdefined( self.perk_data["bullet_damage_scalar"] ) )
        return self.perk_data["bullet_damage_scalar"];
    else
        return self.perk_data["impact"].bullet_damage_scalar;
}

perk_getrevivetimescalar()
{
    if ( isdefined( self.perk_data["revive_time_scalar"] ) )
        return self.perk_data["revive_time_scalar"];
    else
        return self.perk_data["medic"].revive_time_scalar;
}

perk_getmovespeedscalar()
{
    if ( isdefined( self.perk_data["move_speed_scalar"] ) )
        return self.perk_data["move_speed_scalar"];
    else
        return self.perk_data["medic"].move_speed_scalar;
}

perk_getrevivedamagescalar()
{
    if ( isdefined( self.perk_data["revive_damage_scalar"] ) )
        return self.perk_data["revive_damage_scalar"];
    else
        return self.perk_data["medic"].revive_damage_scalar;
}

perk_getexplosivedamagescalar()
{
    if ( isdefined( self.perk_data["explosive_damage_scalar"] ) )
        return self.perk_data["explosive_damage_scalar"];
    else
        return self.perk_data["demolition"].explosive_damage_scalar;
}

perk_getoffhandcount()
{
    if ( isdefined( self.perk_data["offhand_count"] ) )
        return self.perk_data["offhand_count"];
    else
        return self.perk_data["demolition"].offhand_count;
}
