// IW9 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

_id_E3D9D27A30E4D693( target )
{
    return _id_0D74AE0B4AA21186::_id_FF35A4D756374EDE( "Buy", target, "main", target._id_7148C1A6F25491F8 + "/" + target.itemname, ::_id_35671B7B1A04BF58, self, ::_id_F4CAAE7E8AF9D32C );
}

_id_35671B7B1A04BF58( bot )
{
    target = self._id_EC02147FEE952CE2;

    if ( !isdefined( target ) )
        return "Target is undefined";

    targetpos = _id_B454FB48A26AA2C7( target._id_2FA65F34EB9042F5 );
    bot _id_40E63DD222434655::_id_9E400058EF021B03( targetpos, 32 );

    for (;;)
    {
        result = scripts\engine\utility::waittill_any_ents_or_timeout_return( 15, bot, "goal", bot, "bad_path" );

        if ( result == "goal" )
        {
            bot _id_40E63DD222434655::_id_8B201BCCC0AA3695( target._id_2FA65F34EB9042F5.origin, 0.5 );
            bot botpressbutton( "use", 0.25 );
            wait 1.5;
            _id_4F98C366C1BA6F75 = bot.plundercount;
            bot.armorykioskpurchaseallowed = 1;
            bot _id_4384ABBF498DF6A7::onarmorykioskpurchase( target._id_7148C1A6F25491F8, target._id_1657E74C9190D2A2 );

            if ( _id_4F98C366C1BA6F75 >= bot.plundercount )
                _id_6789BD08CBABDB47( target._id_2FA65F34EB9042F5, bot );

            break;
        }
        else if ( result == "bad_path" )
            return result;
    }
}

_id_B454FB48A26AA2C7( _id_2FA65F34EB9042F5 )
{
    _id_90A93951E4C15E03 = 32;
    pos = _id_2FA65F34EB9042F5.origin + anglestoforward( _id_2FA65F34EB9042F5.angles ) * _id_90A93951E4C15E03;
    return getclosestpointonnavmesh( pos );
}

_id_6789BD08CBABDB47( _id_2FA65F34EB9042F5, bot )
{
    if ( !isdefined( _id_2FA65F34EB9042F5._id_19C6F51451310013 ) )
        _id_2FA65F34EB9042F5._id_19C6F51451310013 = [];

    _id_2FA65F34EB9042F5._id_19C6F51451310013[bot.entity_number] = gettime();
}

_id_F4CAAE7E8AF9D32C( action )
{
    self.armorykioskpurchaseallowed = undefined;
}
